screen = {
    'screen_10_confirmation': ['btn_ico_back', 'btn_ok', 'btn_back'],
    'screen_11_tool_issued': ['btn_ico_back', 'btn_back'],
    'screen_12_no_tool': ['btn_ico_back', 'btn_back'],
    'screen_13_no_right': ['btn_ico_back', 'btn_back'],
    'screen_14_stockman': ['btn_warehouse_group', 'btn_back', 'btn_ico_back', 'btn_select_group', 'btn_mass_drop',
                           'btn_summary', 'btn_mass_load'],
    'screen_15_mass_load': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_ok', 'btn_up', 'btn_ico_down'],
    'screen_16_mass_load_ok': ['btn_ico_back', 'btn_back'],
    'screen_17_mass_drop': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_ok', 'btn_up', 'btn_ico_down'],
    'screen_18_mass_drop_ok': ['btn_ico_back', 'btn_back'],
    'screen_19_management_group': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_1_welcome': ['btn_help', 'btn_authorization'],
    'screen_20_management_tool': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_ok', 'btn_up',
                                  'btn_ico_down'],
    'screen_21_summary': ['btn_ico_up', 'btn_select_plans', 'btn_back', 'btn_ico_back', 'btn_select_users', 'btn_down',
                          'btn_up', 'btn_ico_down'],
    'screen_22_users': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_23_plans': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_24_history_by_plan': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_25_history_by_user': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_26_admin': ['btn_reboot', 'btn_back', 'btn_ico_back', 'btn_history_err', 'btn_off', 'btn_serial',
                        'btn_net'],
    'screen_27_history_err': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_28_net_options': ['btn_number_5', 'btn_number_7', 'btn_number_0', 'btn_back', 'btn_number_9',
                              'btn_ico_back', 'btn_number_4', 'btn_number_8', 'btn_number_3', 'btn_number_6',
                              'btn_ping', 'btn_number_2', 'btn_ok', 'btn_number_1'],
    'screen_29_serial_options': ['btn_ico_keyboard', 'btn_insert', 'btn_test', 'btn_back', 'btn_keyboard',
                                 'btn_ico_back', 'btn_ico_insert', 'btn_ok'],
    'screen_2_help': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_30_shutdown': ['btn_ico_back', 'btn_ok', 'btn_back'],
    'screen_31_reboot': ['btn_ico_back', 'btn_ok', 'btn_back'],
    'screen_32_wait': ['btn_help', 'btn_ico_info', 'btn_ico_login', 'btn_login'],
    'screen_3_authorization': ['btn_ico_keyboard', 'btn_back', 'btn_keyboard', 'btn_ico_back', 'btn_authorization'],
    'screen_4_authorization_err': ['btn_ico_back', 'btn_back'],
    'screen_5_identification_err': ['btn_ico_back', 'btn_back'],
    'screen_6_user': ['btn_ico_back', 'btn_back', 'btn_select_group'],
    'screen_7_select_group': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_8_select_tool': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_9_select_tool_by_plan': ['btn_ico_up', 'btn_back', 'btn_ico_back', 'btn_down', 'btn_up', 'btn_ico_down'],
    'screen_33_select_plan': ['btn_back'],
    'screen_35_plan_complete_confirmation': ['btn_ok', 'btn_back'],
    'screen_36_hardware_err': ['btn_back'],
    'screen_37_engineer_hub': ['btn_back', 'btn_hal_coords', 'btn_hal_dispense', 'btn_hal_cells_table'],
    'screen_38_hal_coords': [
        'btn_back', 'btn_hal_park', 'btn_hal_zero', 'btn_hal_save_coords', 'btn_hal_mot_send',
        'hal_jog_z_minus', 'hal_jog_z_plus',
        'hal_jog_m3_minus', 'hal_jog_m3_plus', 'hal_jog_m4_minus', 'hal_jog_m4_plus',
        'hal_jog_m5_minus', 'hal_jog_m5_plus',
    ],
    'screen_40_hal_dispense': [
        'btn_back',
        'btn_hal_dispense_run',
        'btn_hal_park_save',
        'btn_hal_led',
        'btn_hal_solenoid',
        'btn_hal_lock',
    ],
    'screen_41_hal_cells_table': ['btn_back'],
}
