# -*- coding: utf-8 -*-

from StateMachine.screens import screen

states = [
    {'name': 'screen_1_welcome'},
    {'name': 'write_db_help'},
    {'name': 'read_db_help'},
    {'name': 'read_db_groups'},
    {'name': 'read_db_tools_by_group_id'},
    {'name': 'read_cnf'},
    {'name': 'read_db_operations'},
    {'name': 'read_db_mass_load_tools_by_plan'},
    {'name': 'read_db_mass_drop_tools_by_plan'},
    {'name': 'read_db_tools_by_plans_id'},
    {'name': 'read_db_mass_load_tools_by_free'},
    {'name': 'read_db_rights_by_user_id'},
    {'name': 'read_db_mass_drop_tools_by_free'},
    {'name': 'write_db_rights_by_user_id'},
    {'name': 'write_db_mass_drop_tools_by_free'},
    {'name': 'write_db_users'},
    {'name': 'write_cnf_unlock_drop'},
    {'name': 'read_db_plans'},
    {'name': 'write_db_mass_load_tools_by_free'},
    {'name': 'write_db_plans'},
    {'name': 'read_db_users'},
    {'name': 'write_cnf_unlock_load'},
    {'name': 'read_db_err'},
    {'name': 'http_post_request_send_data'},
    {'name': 'http_parse_answer'},
    {'name': 'write_db_mass_drop_tools_by_plan'},
    {'name': 'read_db_history'},
    {'name': 'write_cnf_unlock_drop'},
    {'name': 'http_wait_get_answer'},
    {'name': 'cmd_empty'},
    {'name': 'cmd_run_timeout_post_back'},
    {'name': 'write_db_mass_load_tools_by_plan'},
    {'name': 'cmd_run_timeout_wait_back'},
    {'name': 'cmd_run_timeout_get_back'},
    {'name': 'write_cnf_unlock_load'},
    {'name': 'http_wait_post_answer'},
    {'name': 'read_db_help'},
    {'name': 'cmd_start'},
    {'name': 'cmd_test_self'},
    {'name': 'screen_32_wait'},
    {'name': 'screen_2_help'},
    {'name': 'write_db_tool_consumption'},
    {'name': 'http_get_request_take_command'},
    {'name': 'write_db_err_request'},
    {'name': 'cmd_reboot'},
    {'name': 'cmd_send'},
    {'name': 'read_db_get_more_cells'},
    {'name': 'screen_11_tool_issued'},
    {'name': 'write_db_err_devices'},
    {'name': 'cmd_run_timer_event'},
    {'name': 'write_db_err_timeout'},
    {'name': 'cmd_stop'},
    {'name': 'read_cnf_signature'},
    {'name': 'read_db_get_cell'},
    {'name': 'screen_12_no_tool'},
    {'name': 'write_log_critical_err'},
    {'name': 'write_db_err_devices'},
    {'name': 'screen_10_confirmation'},
    {'name': 'write_db_err_rights'},
    {'name': 'read_db_get_cells'},
    {'name': 'screen_13_no_right'},
    {'name': 'screen_4_authorization_err'},
    {'name': 'cmd_test_is_free'},
    {'name': 'read_db_rights_tool'},
    {'name': 'cmd_ping'},
    {'name': 'screen_27_history_err'},
    {'name': 'write_db_err_login'},
    {'name': 'screen_9_select_tool_by_plan'},
    {'name': 'screen_29_serial_options'},
    {'name': 'screen_6_user'},
    {'name': 'screen_28_net_options'},
    {'name': 'read_db_plan_id'},
    {'name': 'read_db_user_from_barcode'},
    {'name': 'read_db_get_tools'},
    {'name': 'read_db_groups'},
    {'name': 'read_cnf_serial'},
    {'name': 'screen_3_authorization'},
    {'name': 'write_db_err_barcode_user'},
    {'name': 'write_db_err_barcode_plan'},
    {'name': 'write_db_err_get_tools_by_plan_id'},
    {'name': 'read_db_err_history'},
    {'name': 'read_cnf_IP'},
    {'name': 'read_db_username'},
    {'name': 'screen_7_select_group'},
    {'name': 'read_db_tool_names'},
    {'name': 'write_cnf_serial'},
    {'name': 'write_cnf_IP'},
    {'name': 'cmd_keyboard_toggle'},
    {'name': 'screen_31_reboot'},
    {'name': 'screen_5_identification_err'},
    {'name': 'read_db_authorization'},
    {'name': 'screen_8_select_tool'},
    {'name': 'screen_26_admin'},
    {'name': 'read_db_summary'},
    {'name': 'read_db_plans'},
    {'name': 'screen_15_mass_load'},
    {'name': 'write_cnf_lock_load'},
    {'name': 'screen_21_summary'},
    {'name': 'screen_30_shutdown'},
    {'name': 'screen_23_plans'},
    {'name': 'read_db_mass_load_tools'},
    {'name': 'write_db_load_tool_groups'},
    {'name': 'read_db_group_collection'},
    {'name': 'read_db_users'},
    {'name': 'screen_14_stockman'},
    {'name': 'read_db_plan_operations'},
    {'name': 'read_cnf_lock_load'},
    {'name': 'screen_16_mass_load_ok'},
    {'name': 'screen_19_management_group'},
    {'name': 'read_cnf_lock_drop'},
    {'name': 'screen_22_users'},
    {'name': 'screen_18_mass_drop_ok'},
    {'name': 'screen_24_history_by_plan'},
    {'name': 'read_db_mass_drop_tools'},
    {'name': 'read_db_tools_collection'},
    {'name': 'write_db_drop_tool_groups'},
    {'name': 'read_db_user_operations'},
    {'name': 'screen_17_mass_drop'},
    {'name': 'write_cnf_lock_drop'},
    {'name': 'screen_25_history_by_user'},
    {'name': 'read_db_get_plan_tools'},
    {'name': 'screen_20_management_tool'},
    {'name': 'read_db_plan'},
    {'name': 'screen_33_select_plan'},
]

transitions = [
    {'trigger': 'btn_authorization', 'source': 'screen_1_welcome', 'dest': 'screen_3_authorization'},
    {'trigger': 'barcode', 'source': 'screen_1_welcome', 'dest': 'read_db_user_from_barcode'},
    {'trigger': 'err_critical', 'source': 'screen_1_welcome', 'dest': 'write_log_critical_err'},
    {'trigger': 'timer_event', 'source': 'screen_1_welcome', 'dest': 'read_cnf_signature'},
    {'trigger': 'btn_help', 'source': 'screen_1_welcome', 'dest': 'read_db_help'},
    {'trigger': 'write_err', 'source': 'write_db_help', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_ok', 'source': 'write_db_help', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_help', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_groups', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_tools_by_group_id', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_cnf', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_operations', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_mass_load_tools_by_plan', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_mass_drop_tools_by_plan', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_tools_by_plans_id', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_mass_load_tools_by_free', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_rights_by_user_id', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_mass_drop_tools_by_free', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_err', 'source': 'write_db_rights_by_user_id', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_ok', 'source': 'write_db_rights_by_user_id', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_ok', 'source': 'write_db_mass_drop_tools_by_free', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_err', 'source': 'write_db_mass_drop_tools_by_free', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_err', 'source': 'write_db_users', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_ok', 'source': 'write_db_users', 'dest': 'http_post_request_send_data'},
    {'trigger': 'cnf_ok', 'source': 'write_cnf_unlock_drop', 'dest': 'write_db_mass_drop_tools_by_free'},
    {'trigger': 'data', 'source': 'read_db_plans', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_ok', 'source': 'write_db_mass_load_tools_by_free', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_err', 'source': 'write_db_mass_load_tools_by_free', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_err', 'source': 'write_db_plans', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_ok', 'source': 'write_db_plans', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_users', 'dest': 'http_post_request_send_data'},
    {'trigger': 'cnf_ok', 'source': 'write_cnf_unlock_load', 'dest': 'write_db_mass_load_tools_by_free'},
    {'trigger': 'data', 'source': 'read_db_err', 'dest': 'http_post_request_send_data'},
    {'trigger': 'send_request_post', 'source': 'http_post_request_send_data', 'dest': 'cmd_run_timeout_post_back'},
    {'trigger': 'set_plans', 'source': 'http_post_request_send_data', 'dest': 'write_db_plans'},
    {'trigger': 'get_cnf', 'source': 'http_parse_answer', 'dest': 'read_cnf'},
    {'trigger': 'get_mass_drop_tools_by_plan', 'source': 'http_parse_answer', 'dest': 'read_db_mass_drop_tools_by_plan'},
    {'trigger': 'empty', 'source': 'http_parse_answer', 'dest': 'cmd_empty'},
    {'trigger': 'get_rights_by_user_id', 'source': 'http_parse_answer', 'dest': 'write_db_rights_by_user_id'},
    {'trigger': 'get_users', 'source': 'http_parse_answer', 'dest': 'read_db_users'},
    {'trigger': 'get_users', 'source': 'http_parse_answer', 'dest': 'write_db_users'},
    {'trigger': 'get_rights_by_user_id', 'source': 'http_parse_answer', 'dest': 'read_db_rights_by_user_id'},
    {'trigger': 'set_help', 'source': 'http_parse_answer', 'dest': 'write_db_help'},
    {'trigger': 'get_mass_drop_tools_by_free', 'source': 'http_parse_answer', 'dest': 'read_db_mass_drop_tools_by_free'},
    {'trigger': 'get_help', 'source': 'http_parse_answer', 'dest': 'read_db_help'},
    {'trigger': 'get_history', 'source': 'http_parse_answer', 'dest': 'read_db_history'},
    {'trigger': 'set_mass_drop_tools_by_free', 'source': 'http_parse_answer', 'dest': 'write_cnf_unlock_drop'},
    {'trigger': 'get_operations', 'source': 'http_parse_answer', 'dest': 'read_db_operations'},
    {'trigger': 'get_mass_load_tools_by_free', 'source': 'http_parse_answer', 'dest': 'read_db_mass_load_tools_by_free'},
    {'trigger': 'set_mass_load_tools_by_free', 'source': 'http_parse_answer', 'dest': 'write_cnf_unlock_load'},
    {'trigger': 'get_err', 'source': 'http_parse_answer', 'dest': 'read_db_err'},
    {'trigger': 'get_tools_by_plans_id', 'source': 'http_parse_answer', 'dest': 'read_db_tools_by_plans_id'},
    {'trigger': 'get_plans', 'source': 'http_parse_answer', 'dest': 'read_db_plans'},
    {'trigger': 'set_mass_drop_tools_by_plan', 'source': 'http_parse_answer', 'dest': 'write_cnf_unlock_drop'},
    {'trigger': 'set_mass_load_tools_by_plan', 'source': 'http_parse_answer', 'dest': 'write_cnf_unlock_load'},
    {'trigger': 'get_groups', 'source': 'http_parse_answer', 'dest': 'read_db_groups'},
    {'trigger': 'get_command', 'source': 'http_parse_answer', 'dest': 'http_post_request_send_data'},
    {'trigger': 'get_tools_by_group_id', 'source': 'http_parse_answer', 'dest': 'read_db_tools_by_group_id'},
    {'trigger': 'get_mass_load_tools_by_plan', 'source': 'http_parse_answer', 'dest': 'read_db_mass_load_tools_by_plan'},
    {'trigger': 'write_ok', 'source': 'write_db_mass_drop_tools_by_plan', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_err', 'source': 'write_db_mass_drop_tools_by_plan', 'dest': 'http_post_request_send_data'},
    {'trigger': 'data', 'source': 'read_db_history', 'dest': 'http_post_request_send_data'},
    {'trigger': 'set_mass_drop_data', 'source': 'write_cnf_unlock_drop', 'dest': 'write_db_mass_drop_tools_by_plan'},
    {'trigger': 'timeout_err', 'source': 'http_wait_get_answer', 'dest': 'write_db_err_request'},
    {'trigger': 'received_command', 'source': 'http_wait_get_answer', 'dest': 'http_parse_answer'},
    {'trigger': 'ok', 'source': 'cmd_empty', 'dest': 'screen_1_welcome'},
    {'trigger': 'wait_run', 'source': 'cmd_run_timeout_post_back', 'dest': 'http_wait_post_answer'},
    {'trigger': 'write_ok', 'source': 'write_db_mass_load_tools_by_plan', 'dest': 'http_post_request_send_data'},
    {'trigger': 'write_err', 'source': 'write_db_mass_load_tools_by_plan', 'dest': 'http_post_request_send_data'},
    {'trigger': 'view_wait', 'source': 'cmd_run_timeout_wait_back', 'dest': 'screen_32_wait'},
    {'trigger': 'wait_run', 'source': 'cmd_run_timeout_get_back', 'dest': 'http_wait_get_answer'},
    {'trigger': 'set_mass_load_data', 'source': 'write_cnf_unlock_load', 'dest': 'write_db_mass_load_tools_by_plan'},
    {'trigger': 'received_ok', 'source': 'http_wait_post_answer', 'dest': 'http_parse_answer'},
    {'trigger': 'timeout_err', 'source': 'http_wait_post_answer', 'dest': 'write_db_err_request'},
    {'trigger': 'multiline_text', 'source': 'read_db_help', 'dest': 'screen_2_help'},
    {'trigger': 'system_start', 'source': 'cmd_start', 'dest': 'cmd_test_self'},
    {'trigger': 'ok', 'source': 'cmd_test_self', 'dest': 'cmd_run_timer_event'},
    {'trigger': 'err_critical', 'source': 'cmd_test_self', 'dest': 'write_log_critical_err'},
    {'trigger': 'command_is_send', 'source': 'screen_32_wait', 'dest': 'screen_32_wait'},
    {'trigger': 'err_devices', 'source': 'screen_32_wait', 'dest': 'write_db_err_devices'},
    {'trigger': 'command_ok', 'source': 'screen_32_wait', 'dest': 'write_db_tool_consumption'},
    {'trigger': 'timeout_back', 'source': 'screen_32_wait', 'dest': 'write_db_err_timeout'},
    {'trigger': 'btn_back', 'source': 'screen_2_help', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_up', 'source': 'screen_2_help', 'dest': 'read_db_help'},
    {'trigger': 'btn_down', 'source': 'screen_2_help', 'dest': 'read_db_help'},
    {'trigger': 'timeout_back', 'source': 'screen_2_help', 'dest': 'screen_1_welcome'},
    {'trigger': 'view_ok', 'source': 'write_db_tool_consumption', 'dest': 'screen_11_tool_issued'},
    {'trigger': 'view_err', 'source': 'write_db_tool_consumption', 'dest': 'screen_12_no_tool'},
    {'trigger': 'get_more_cells', 'source': 'write_db_tool_consumption', 'dest': 'read_db_get_more_cells'},
    {'trigger': 'cmd_empty', 'source': 'http_get_request_take_command', 'dest': 'cmd_empty'},
    {'trigger': 'send_request_get', 'source': 'http_get_request_take_command', 'dest': 'cmd_run_timeout_get_back'},
    {'trigger': 'back_err', 'source': 'write_db_err_request', 'dest': 'screen_1_welcome'},
    {'trigger': 'err_devices', 'source': 'cmd_send', 'dest': 'write_db_err_devices'},
    {'trigger': 'command_is_send', 'source': 'cmd_send', 'dest': 'cmd_run_timeout_wait_back'},
    {'trigger': 'send_number', 'source': 'read_db_get_more_cells', 'dest': 'cmd_send'},
    {'trigger': 'err_data', 'source': 'read_db_get_more_cells', 'dest': 'write_db_err_rights'},
    {'trigger': 'view_ok', 'source': 'read_db_get_more_cells', 'dest': 'screen_11_tool_issued'},
    {'trigger': 'btn_back', 'source': 'screen_11_tool_issued', 'dest': 'screen_1_welcome'},
    {'trigger': 'timeout_back', 'source': 'screen_11_tool_issued', 'dest': 'screen_1_welcome'},
    {'trigger': 'command_is_send', 'source': 'screen_11_tool_issued', 'dest': 'screen_11_tool_issued'},
    {'trigger': 'view_err', 'source': 'write_db_err_devices', 'dest': 'screen_12_no_tool'},
    {'trigger': 'ready_to_use', 'source': 'cmd_run_timer_event', 'dest': 'screen_1_welcome'},
    {'trigger': 'view_err', 'source': 'write_db_err_timeout', 'dest': 'screen_12_no_tool'},
    {'trigger': 'get_token', 'source': 'read_cnf_signature', 'dest': 'http_get_request_take_command'},
    {'trigger': 'send_number', 'source': 'read_db_get_cell', 'dest': 'cmd_send'},
    {'trigger': 'err_data', 'source': 'read_db_get_cell', 'dest': 'write_db_err_rights'},
    {'trigger': 'btn_back', 'source': 'screen_12_no_tool', 'dest': 'screen_1_welcome'},
    {'trigger': 'timeout_back', 'source': 'screen_12_no_tool', 'dest': 'screen_1_welcome'},
    {'trigger': 'system_stop', 'source': 'write_log_critical_err', 'dest': 'cmd_stop'},
    {'trigger': 'view_err', 'source': 'write_db_err_devices', 'dest': 'screen_12_no_tool'},
    {'trigger': 'btn_back', 'source': 'screen_10_confirmation', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_ok', 'source': 'screen_10_confirmation', 'dest': 'read_db_get_cell'},
    {'trigger': 'timeout_back', 'source': 'screen_10_confirmation', 'dest': 'screen_1_welcome'},
    {'trigger': 'view_err_rights', 'source': 'write_db_err_rights', 'dest': 'screen_13_no_right'},
    {'trigger': 'err_data', 'source': 'read_db_get_cells', 'dest': 'write_db_err_rights'},
    {'trigger': 'get_more_cells', 'source': 'read_db_get_cells', 'dest': 'read_db_get_more_cells'},
    {'trigger': 'btn_back', 'source': 'screen_13_no_right', 'dest': 'screen_1_welcome'},
    {'trigger': 'timeout_back', 'source': 'screen_13_no_right', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_4_authorization_err', 'dest': 'screen_1_welcome'},
    {'trigger': 'timeout_back', 'source': 'screen_4_authorization_err', 'dest': 'screen_1_welcome'},
    {'trigger': 'status', 'source': 'cmd_test_is_free', 'dest': 'screen_29_serial_options'},
    {'trigger': 'view_get_tool', 'source': 'read_db_rights_tool', 'dest': 'screen_10_confirmation'},
    {'trigger': 'err_rights', 'source': 'read_db_rights_tool', 'dest': 'write_db_err_rights'},
    {'trigger': 'status', 'source': 'cmd_ping', 'dest': 'screen_28_net_options'},
    {'trigger': 'btn_down', 'source': 'screen_27_history_err', 'dest': 'read_db_err_history'},
    {'trigger': 'btn_up', 'source': 'screen_27_history_err', 'dest': 'read_db_err_history'},
    {'trigger': 'timeout_back', 'source': 'screen_27_history_err', 'dest': 'screen_1_welcome'},
    {'trigger': 'view_err_login', 'source': 'write_db_err_login', 'dest': 'screen_4_authorization_err'},
    {'trigger': 'timeout_back', 'source': 'screen_9_select_tool_by_plan', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_tool_name', 'source': 'screen_9_select_tool_by_plan', 'dest': 'read_db_rights_tool'},
    {'trigger': 'btn_back', 'source': 'screen_9_select_tool_by_plan', 'dest': 'read_db_plan'},
    {'trigger': 'btn_ok', 'source': 'screen_9_select_tool_by_plan', 'dest': 'read_db_get_cells'},
    {'trigger': 'timeout_back', 'source': 'screen_29_serial_options', 'dest': 'screen_1_welcome'},
    {'trigger': 'test', 'source': 'screen_29_serial_options', 'dest': 'cmd_test_is_free'},
    {'trigger': 'btn_ok', 'source': 'screen_29_serial_options', 'dest': 'write_cnf_serial'},
    {'trigger': 'timeout_back', 'source': 'screen_6_user', 'dest': 'screen_1_welcome'},
    {'trigger': 'barcode', 'source': 'screen_6_user', 'dest': 'read_db_plan_id'},
    {'trigger': 'btn_back', 'source': 'screen_6_user', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_select_group', 'source': 'screen_6_user', 'dest': 'read_db_groups'},
    {'trigger': 'btn_ok', 'source': 'screen_28_net_options', 'dest': 'write_cnf_IP'},
    {'trigger': 'test', 'source': 'screen_28_net_options', 'dest': 'cmd_ping'},
    {'trigger': 'btn_back', 'source': 'screen_28_net_options', 'dest': 'screen_26_admin'},
    {'trigger': 'timeout_back', 'source': 'screen_28_net_options', 'dest': 'screen_1_welcome'},
    {'trigger': 'plan_id', 'source': 'read_db_plan_id', 'dest': 'read_db_get_tools'},
    {'trigger': 'send_number', 'source': 'read_db_plan_id', 'dest': 'cmd_send'},
    {'trigger': 'err_barcode', 'source': 'read_db_plan_id', 'dest': 'write_db_err_barcode_plan'},
    {'trigger': 'user_name', 'source': 'read_db_user_from_barcode', 'dest': 'screen_6_user'},
    {'trigger': 'err_barcode', 'source': 'read_db_user_from_barcode', 'dest': 'write_db_err_barcode_user'},
    {'trigger': 'view_tools', 'source': 'read_db_get_tools', 'dest': 'screen_9_select_tool_by_plan'},
    {'trigger': 'err_get_tools_by_plan_id', 'source': 'read_db_get_tools', 'dest': 'write_db_err_get_tools_by_plan_id'},
    {'trigger': 'view_tool_groups', 'source': 'read_db_groups', 'dest': 'screen_7_select_group'},
    {'trigger': 'view_cnf_serial', 'source': 'read_cnf_serial', 'dest': 'screen_29_serial_options'},
    {'trigger': 'edit_psw', 'source': 'screen_3_authorization', 'dest': 'cmd_keyboard_toggle'},
    {'trigger': 'btn_authorization', 'source': 'screen_3_authorization', 'dest': 'read_db_authorization'},
    {'trigger': 'timeout_back', 'source': 'screen_3_authorization', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_3_authorization', 'dest': 'screen_1_welcome'},
    {'trigger': 'edit_login', 'source': 'screen_3_authorization', 'dest': 'cmd_keyboard_toggle'},
    {'trigger': 'btn_keyboard', 'source': 'screen_3_authorization', 'dest': 'cmd_keyboard_toggle'},
    {'trigger': 'input_name_code', 'source': 'screen_3_authorization', 'dest': 'read_db_username'},
    {'trigger': 'view_err', 'source': 'write_db_err_barcode_user', 'dest': 'screen_5_identification_err'},
    {'trigger': 'view_err', 'source': 'write_db_err_barcode_plan', 'dest': 'screen_5_identification_err'},
    {'trigger': 'view_err', 'source': 'write_db_err_get_tools_by_plan_id', 'dest': 'screen_5_identification_err'},
    {'trigger': 'view_history_err', 'source': 'read_db_err_history', 'dest': 'screen_27_history_err'},
    {'trigger': 'view_cnf_IP', 'source': 'read_cnf_IP', 'dest': 'screen_28_net_options'},
    {'trigger': 'view_user_name', 'source': 'read_db_username', 'dest': 'screen_3_authorization'},
    {'trigger': 'err_authorization', 'source': 'read_db_username', 'dest': 'write_db_err_login'},
    {'trigger': 'btn_select_group_names', 'source': 'screen_7_select_group', 'dest': 'read_db_tool_names'},
    {'trigger': 'btn_back', 'source': 'screen_7_select_group', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_up', 'source': 'screen_7_select_group', 'dest': 'read_db_groups'},
    {'trigger': 'btn_down', 'source': 'screen_7_select_group', 'dest': 'read_db_groups'},
    {'trigger': 'timeout_back', 'source': 'screen_7_select_group', 'dest': 'screen_1_welcome'},
    {'trigger': 'view_tool_names', 'source': 'read_db_tool_names', 'dest': 'screen_8_select_tool'},
    {'trigger': 'ok', 'source': 'write_cnf_serial', 'dest': 'screen_26_admin'},
    {'trigger': 'ok', 'source': 'write_cnf_IP', 'dest': 'screen_26_admin'},
    {'trigger': 'keyboard_status', 'source': 'cmd_keyboard_toggle', 'dest': 'screen_3_authorization'},
    {'trigger': 'timeout_back', 'source': 'screen_31_reboot', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_ok', 'source': 'screen_31_reboot', 'dest': 'cmd_reboot'},
    {'trigger': 'timeout_back', 'source': 'screen_5_identification_err', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_5_identification_err', 'dest': 'screen_1_welcome'},
    {'trigger': 'type_storekeeper', 'source': 'read_db_authorization', 'dest': 'screen_14_stockman'},
    {'trigger': 'test_user', 'source': 'read_db_authorization', 'dest': 'screen_6_user'},
    {'trigger': 'err_authorization', 'source': 'read_db_authorization', 'dest': 'write_db_err_login'},
    {'trigger': 'view_type_admin', 'source': 'read_db_authorization', 'dest': 'screen_26_admin'},
    {'trigger': 'btn_back', 'source': 'screen_8_select_tool', 'dest': 'read_db_groups'},
    {'trigger': 'btn_down', 'source': 'screen_8_select_tool', 'dest': 'read_db_tool_names'},
    {'trigger': 'btn_up', 'source': 'screen_8_select_tool', 'dest': 'read_db_tool_names'},
    {'trigger': 'btn_tool_name', 'source': 'screen_8_select_tool', 'dest': 'read_db_rights_tool'},
    {'trigger': 'timeout_back', 'source': 'screen_8_select_tool', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_30_shutdown', 'dest': 'screen_26_admin'},
    {'trigger': 'btn_history_err', 'source': 'screen_26_admin', 'dest': 'read_db_err_history'},
    {'trigger': 'btn_off', 'source': 'screen_26_admin', 'dest': 'screen_30_shutdown'},
    {'trigger': 'btn_serial', 'source': 'screen_26_admin', 'dest': 'read_cnf_serial'},
    {'trigger': 'btn_back', 'source': 'screen_26_admin', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_summary', 'source': 'screen_26_admin', 'dest': 'read_db_summary'},
    {'trigger': 'btn_reboot', 'source': 'screen_26_admin', 'dest': 'screen_31_reboot'},
    {'trigger': 'btn_net', 'source': 'screen_26_admin', 'dest': 'read_cnf_IP'},
    {'trigger': 'btn_back', 'source': 'screen_27_history_err', 'dest': 'screen_26_admin'},
    {'trigger': 'timeout_back', 'source': 'screen_26_admin', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_31_reboot', 'dest': 'screen_26_admin'},
    {'trigger': 'view_summary', 'source': 'read_db_summary', 'dest': 'screen_21_summary'},
    {'trigger': 'view_plans', 'source': 'read_db_plans', 'dest': 'screen_23_plans'},
    {'trigger': 'btn_load_ok', 'source': 'screen_15_mass_load', 'dest': 'write_cnf_lock_load'},
    {'trigger': 'btn_down', 'source': 'screen_15_mass_load', 'dest': 'read_db_mass_load_tools'},
    {'trigger': 'btn_up', 'source': 'screen_15_mass_load', 'dest': 'read_db_mass_load_tools'},
    {'trigger': 'timeout_back', 'source': 'screen_15_mass_load', 'dest': 'screen_1_welcome'},
    {'trigger': 'load_ok', 'source': 'write_cnf_lock_load', 'dest': 'write_db_load_tool_groups'},
    {'trigger': 'timeout_back', 'source': 'screen_21_summary', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_21_summary', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_22_users', 'dest': 'screen_21_summary'},
    {'trigger': 'btn_select_users', 'source': 'screen_21_summary', 'dest': 'read_db_users'},
    {'trigger': 'btn_up', 'source': 'screen_21_summary', 'dest': 'read_db_summary'},
    {'trigger': 'btn_select_plans', 'source': 'screen_21_summary', 'dest': 'read_db_plans'},
    {'trigger': 'btn_back', 'source': 'screen_23_plans', 'dest': 'screen_21_summary'},
    {'trigger': 'btn_down', 'source': 'screen_21_summary', 'dest': 'read_db_summary'},
    {'trigger': 'timeout_back', 'source': 'screen_30_shutdown', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_ok', 'source': 'screen_30_shutdown', 'dest': 'cmd_stop'},
    {'trigger': 'timeout_back', 'source': 'screen_23_plans', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_down', 'source': 'screen_23_plans', 'dest': 'read_db_plans'},
    {'trigger': 'btn_plan_id_history', 'source': 'screen_23_plans', 'dest': 'read_db_plan_operations'},
    {'trigger': 'btn_back', 'source': 'screen_24_history_by_plan', 'dest': 'screen_23_plans'},
    {'trigger': 'btn_down', 'source': 'screen_23_plans', 'dest': 'read_db_plans'},
    {'trigger': 'view_mass_load_tools', 'source': 'read_db_mass_load_tools', 'dest': 'screen_15_mass_load'},
    {'trigger': 'view_mass_load_ok', 'source': 'write_db_load_tool_groups', 'dest': 'screen_16_mass_load_ok'},
    {'trigger': 'view_warehouse_group', 'source': 'read_db_group_collection', 'dest': 'screen_19_management_group'},
    {'trigger': 'view_users', 'source': 'read_db_users', 'dest': 'screen_22_users'},
    {'trigger': 'btn_select_group', 'source': 'screen_14_stockman', 'dest': 'read_db_groups'},
    {'trigger': 'btn_summary', 'source': 'screen_14_stockman', 'dest': 'read_db_summary'},
    {'trigger': 'btn_back', 'source': 'screen_17_mass_drop', 'dest': 'screen_14_stockman'},
    {'trigger': 'btn_back', 'source': 'screen_15_mass_load', 'dest': 'screen_14_stockman'},
    {'trigger': 'barcode', 'source': 'screen_14_stockman', 'dest': 'read_db_plan_id'},
    {'trigger': 'timeout_back', 'source': 'screen_14_stockman', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_mass_load', 'source': 'screen_14_stockman', 'dest': 'read_cnf_lock_load'},
    {'trigger': 'btn_mass_drop', 'source': 'screen_14_stockman', 'dest': 'read_cnf_lock_drop'},
    {'trigger': 'btn_back', 'source': 'screen_14_stockman', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_warehouse_group', 'source': 'screen_14_stockman', 'dest': 'read_db_group_collection'},
    {'trigger': 'btn_select_plan', 'source': 'screen_14_stockman', 'dest': 'read_db_plan'},
    {'trigger': 'view_plan_operations', 'source': 'read_db_plan_operations', 'dest': 'screen_24_history_by_plan'},
    {'trigger': 'unlock', 'source': 'read_cnf_lock_load', 'dest': 'read_db_mass_load_tools'},
    {'trigger': 'lock', 'source': 'read_cnf_lock_load', 'dest': 'screen_14_stockman'},
    {'trigger': 'btn_back', 'source': 'screen_16_mass_load_ok', 'dest': 'screen_1_welcome'},
    {'trigger': 'timeout_back', 'source': 'screen_16_mass_load_ok', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_up', 'source': 'screen_19_management_group', 'dest': 'read_db_group_collection'},
    {'trigger': 'btn_warehouse_select_tools', 'source': 'screen_19_management_group', 'dest': 'read_db_tools_collection'},
    {'trigger': 'btn_back', 'source': 'screen_19_management_group', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_down', 'source': 'screen_19_management_group', 'dest': 'read_db_group_collection'},
    {'trigger': 'timeout_back', 'source': 'screen_19_management_group', 'dest': 'screen_1_welcome'},
    {'trigger': 'unlock', 'source': 'read_cnf_lock_drop', 'dest': 'read_db_mass_drop_tools'},
    {'trigger': 'lock', 'source': 'read_cnf_lock_drop', 'dest': 'screen_14_stockman'},
    {'trigger': 'btn_back', 'source': 'screen_25_history_by_user', 'dest': 'screen_22_users'},
    {'trigger': 'btn_user_id', 'source': 'screen_22_users', 'dest': 'read_db_user_operations'},
    {'trigger': 'timeout_back', 'source': 'screen_22_users', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_up', 'source': 'screen_22_users', 'dest': 'read_db_users'},
    {'trigger': 'btn_down', 'source': 'screen_22_users', 'dest': 'read_db_users'},
    {'trigger': 'timeout_back', 'source': 'screen_18_mass_drop_ok', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_back', 'source': 'screen_18_mass_drop_ok', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_up', 'source': 'screen_24_history_by_plan', 'dest': 'read_db_plan_operations'},
    {'trigger': 'btn_down', 'source': 'screen_24_history_by_plan', 'dest': 'read_db_plan_operations'},
    {'trigger': 'timeout_back', 'source': 'screen_24_history_by_plan', 'dest': 'screen_1_welcome'},
    {'trigger': 'mass_drop_tools', 'source': 'read_db_mass_drop_tools', 'dest': 'screen_17_mass_drop'},
    {'trigger': 'view_warehouse_select_tools', 'source': 'read_db_tools_collection', 'dest': 'screen_20_management_tool'},
    {'trigger': 'view_mass_drop_ok', 'source': 'write_db_drop_tool_groups', 'dest': 'screen_18_mass_drop_ok'},
    {'trigger': 'view_user_operations', 'source': 'read_db_user_operations', 'dest': 'screen_25_history_by_user'},
    {'trigger': 'btn_drop_ok', 'source': 'screen_17_mass_drop', 'dest': 'write_cnf_lock_drop'},
    {'trigger': 'timeout_back', 'source': 'screen_17_mass_drop', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_up', 'source': 'screen_17_mass_drop', 'dest': 'read_db_mass_drop_tools'},
    {'trigger': 'btn_down', 'source': 'screen_17_mass_drop', 'dest': 'read_db_mass_drop_tools'},
    {'trigger': 'drop_ok', 'source': 'write_cnf_lock_drop', 'dest': 'write_db_drop_tool_groups'},
    {'trigger': 'btn_up', 'source': 'screen_25_history_by_user', 'dest': 'read_db_user_operations'},
    {'trigger': 'timeout_back', 'source': 'screen_25_history_by_user', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_down', 'source': 'screen_25_history_by_user', 'dest': 'read_db_user_operations'},
    {'trigger': 'view_tools', 'source': 'read_db_get_plan_tools', 'dest': 'screen_9_select_tool_by_plan'},
    {'trigger': 'btn_back', 'source': 'screen_20_management_tool', 'dest': 'screen_1_welcome'},
    {'trigger': 'timeout_back', 'source': 'screen_20_management_tool', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_up', 'source': 'screen_20_management_tool', 'dest': 'read_db_tools_collection'},
    {'trigger': 'btn_down', 'source': 'screen_20_management_tool', 'dest': 'read_db_tools_collection'},
    {'trigger': 'view_plans', 'source': 'read_db_plan', 'dest': 'screen_33_select_plan'},
    {'trigger': 'btn_back', 'source': 'screen_33_select_plan', 'dest': 'screen_14_stockman'},
    {'trigger': 'timeout_back', 'source': 'screen_33_select_plan', 'dest': 'screen_1_welcome'},
    {'trigger': 'btn_plan_name', 'source': 'screen_33_select_plan', 'dest': 'read_db_get_plan_tools'},
]