# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\widgets\widget_select_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_select_group(object):
    def setupUi(self, widget_select_group):
        widget_select_group.setObjectName("widget_select_group")
        widget_select_group.resize(464, 84)
        widget_select_group.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(47, 70, 105, 255), stop:1 rgba(131, 149, 174, 255));\n"
"border-color: rgb(0, 255, 0);")
        self.lbl_photo = QtWidgets.QLabel(widget_select_group)
        self.lbl_photo.setGeometry(QtCore.QRect(5, 5, 213, 70))
        self.lbl_photo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_photo.setText("")
        self.lbl_photo.setPixmap(QtGui.QPixmap("C:/Users/Admin/.designer/backup/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.lbl_photo.setScaledContents(True)
        self.lbl_photo.setObjectName("lbl_photo")
        self.name = QtWidgets.QLabel(widget_select_group)
        self.name.setGeometry(QtCore.QRect(5, 5, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.name.setLineWidth(0)
        self.name.setMidLineWidth(0)
        self.name.setTextFormat(QtCore.Qt.AutoText)
        self.name.setPixmap(QtGui.QPixmap("ui\\widgets\\../../../../../../GUI/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.name.setScaledContents(True)
        self.name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name.setWordWrap(True)
        self.name.setOpenExternalLinks(False)
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(widget_select_group)
        self.label.setGeometry(QtCore.QRect(2, 2, 460, 80))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setObjectName("label")
        self.lbl_count = QtWidgets.QLabel(widget_select_group)
        self.lbl_count.setEnabled(True)
        self.lbl_count.setGeometry(QtCore.QRect(215, 40, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_count.setFont(font)
        self.lbl_count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_count.setStyleSheet("color: rgb(0, 49, 114);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_count.setObjectName("lbl_count")
        self.count = QtWidgets.QLabel(widget_select_group)
        self.count.setEnabled(True)
        self.count.setGeometry(QtCore.QRect(300, 40, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.count.setFont(font)
        self.count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.count.setStyleSheet("color: rgb(0, 49, 114);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.count.setObjectName("count")
        self.label.raise_()
        self.lbl_photo.raise_()
        self.name.raise_()
        self.lbl_count.raise_()
        self.count.raise_()

        self.retranslateUi(widget_select_group)
        QtCore.QMetaObject.connectSlotsByName(widget_select_group)

    def retranslateUi(self, widget_select_group):
        _translate = QtCore.QCoreApplication.translate
        widget_select_group.setWindowTitle(_translate("widget_select_group", "widget_select_group"))
        self.name.setText(_translate("widget_select_group", "Фреза"))
        self.lbl_count.setText(_translate("widget_select_group", "Всего:"))
        self.count.setText(_translate("widget_select_group", "2545"))
