# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\widgets\widget_22_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_22_user(object):
    def setupUi(self, widget_22_user):
        widget_22_user.setObjectName("widget_22_user")
        widget_22_user.resize(440, 75)
        widget_22_user.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(47, 70, 105, 255), stop:1 rgba(131, 149, 174, 255));")
        self.lbl_name_1 = QtWidgets.QLabel(widget_22_user)
        self.lbl_name_1.setEnabled(True)
        self.lbl_name_1.setGeometry(QtCore.QRect(5, 5, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name_1.setFont(font)
        self.lbl_name_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_name_1.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_name_1.setObjectName("lbl_name_1")
        self.lbl_name_2 = QtWidgets.QLabel(widget_22_user)
        self.lbl_name_2.setEnabled(True)
        self.lbl_name_2.setGeometry(QtCore.QRect(247, 5, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name_2.setFont(font)
        self.lbl_name_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_name_2.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_name_2.setObjectName("lbl_name_2")
        self.lbl_info = QtWidgets.QLabel(widget_22_user)
        self.lbl_info.setEnabled(True)
        self.lbl_info.setGeometry(QtCore.QRect(5, 40, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info.setFont(font)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setStyleSheet("color: rgb(0, 49, 114);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_info.setObjectName("lbl_info")
        self.lbl_job_title = QtWidgets.QLabel(widget_22_user)
        self.lbl_job_title.setEnabled(True)
        self.lbl_job_title.setGeometry(QtCore.QRect(245, 40, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_job_title.setFont(font)
        self.lbl_job_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_job_title.setStyleSheet("color: rgb(0, 49, 114);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_job_title.setObjectName("lbl_job_title")

        self.retranslateUi(widget_22_user)
        QtCore.QMetaObject.connectSlotsByName(widget_22_user)

    def retranslateUi(self, widget_22_user):
        _translate = QtCore.QCoreApplication.translate
        widget_22_user.setWindowTitle(_translate("widget_22_user", "widget_22_user"))
        self.lbl_name_1.setText(_translate("widget_22_user", "Романов Александр"))
        self.lbl_name_2.setText(_translate("widget_22_user", "Александрович"))
        self.lbl_info.setText(_translate("widget_22_user", "<html><head/><body><p>Роль:</p></body></html>"))
        self.lbl_job_title.setText(_translate("widget_22_user", "<html><head/><body><p align=\"right\">Администратор</p></body></html>"))
