# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\widgets\widget_3_29_keyboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_3_29_keyboard(object):
    def setupUi(self, widget_3_29_keyboard):
        widget_3_29_keyboard.setObjectName("widget_3_29_keyboard")
        widget_3_29_keyboard.resize(450, 225)
        widget_3_29_keyboard.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"#background {\n"
"    color: #FFFFFF;\n"
"    background-color: #2e4461;\n"
"    border-width: 2px;\n"
"    border-style: groove;\n"
"    border-color: #ff9923;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-style: outset;\n"
"    border-color: #EAA657;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 25px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.btn_number_7 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_7.setEnabled(True)
        self.btn_number_7.setGeometry(QtCore.QRect(5, 115, 143, 50))
        self.btn_number_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_7.setFont(font)
        self.btn_number_7.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_7.setObjectName("btn_number_7")
        self.btn_number_9 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_9.setEnabled(True)
        self.btn_number_9.setGeometry(QtCore.QRect(302, 115, 143, 50))
        self.btn_number_9.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_9.setFont(font)
        self.btn_number_9.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_9.setObjectName("btn_number_9")
        self.btn_number_8 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_8.setEnabled(True)
        self.btn_number_8.setGeometry(QtCore.QRect(153, 115, 144, 50))
        self.btn_number_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_8.setFont(font)
        self.btn_number_8.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_8.setObjectName("btn_number_8")
        self.btn_number_0 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_0.setEnabled(True)
        self.btn_number_0.setGeometry(QtCore.QRect(5, 170, 143, 50))
        self.btn_number_0.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_0.setFont(font)
        self.btn_number_0.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_0.setObjectName("btn_number_0")
        self.btn_number_5 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_5.setEnabled(True)
        self.btn_number_5.setGeometry(QtCore.QRect(153, 60, 144, 50))
        self.btn_number_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_5.setFont(font)
        self.btn_number_5.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_5.setObjectName("btn_number_5")
        self.btn_number_4 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_4.setEnabled(True)
        self.btn_number_4.setGeometry(QtCore.QRect(5, 60, 143, 50))
        self.btn_number_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_4.setFont(font)
        self.btn_number_4.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_4.setObjectName("btn_number_4")
        self.btn_number_3 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_3.setEnabled(True)
        self.btn_number_3.setGeometry(QtCore.QRect(302, 5, 143, 50))
        self.btn_number_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_3.setFont(font)
        self.btn_number_3.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_3.setObjectName("btn_number_3")
        self.btn_number_2 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_2.setEnabled(True)
        self.btn_number_2.setGeometry(QtCore.QRect(153, 5, 144, 50))
        self.btn_number_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_2.setFont(font)
        self.btn_number_2.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_2.setObjectName("btn_number_2")
        self.btn_number_6 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_6.setEnabled(True)
        self.btn_number_6.setGeometry(QtCore.QRect(302, 60, 143, 50))
        self.btn_number_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_6.setFont(font)
        self.btn_number_6.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_6.setObjectName("btn_number_6")
        self.btn_number_1 = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_number_1.setEnabled(True)
        self.btn_number_1.setGeometry(QtCore.QRect(5, 5, 143, 50))
        self.btn_number_1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number_1.setFont(font)
        self.btn_number_1.setIconSize(QtCore.QSize(51, 51))
        self.btn_number_1.setObjectName("btn_number_1")
        self.btn_backspace = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_backspace.setEnabled(True)
        self.btn_backspace.setGeometry(QtCore.QRect(153, 170, 144, 50))
        self.btn_backspace.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_backspace.setFont(font)
        self.btn_backspace.setIconSize(QtCore.QSize(51, 51))
        self.btn_backspace.setObjectName("btn_backspace")
        self.btn_close = QtWidgets.QPushButton(widget_3_29_keyboard)
        self.btn_close.setEnabled(True)
        self.btn_close.setGeometry(QtCore.QRect(302, 170, 143, 50))
        self.btn_close.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_close.setFont(font)
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(51, 51))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(widget_3_29_keyboard)
        QtCore.QMetaObject.connectSlotsByName(widget_3_29_keyboard)

    def retranslateUi(self, widget_3_29_keyboard):
        _translate = QtCore.QCoreApplication.translate
        widget_3_29_keyboard.setWindowTitle(_translate("widget_3_29_keyboard", "widget_3_29_keyboard"))
        self.btn_number_7.setText(_translate("widget_3_29_keyboard", "7"))
        self.btn_number_9.setText(_translate("widget_3_29_keyboard", "9"))
        self.btn_number_8.setText(_translate("widget_3_29_keyboard", "8"))
        self.btn_number_0.setText(_translate("widget_3_29_keyboard", "0"))
        self.btn_number_5.setText(_translate("widget_3_29_keyboard", "5"))
        self.btn_number_4.setText(_translate("widget_3_29_keyboard", "4"))
        self.btn_number_3.setText(_translate("widget_3_29_keyboard", "3"))
        self.btn_number_2.setText(_translate("widget_3_29_keyboard", "2"))
        self.btn_number_6.setText(_translate("widget_3_29_keyboard", "6"))
        self.btn_number_1.setText(_translate("widget_3_29_keyboard", "1"))
        self.btn_backspace.setText(_translate("widget_3_29_keyboard", "⌫"))
from ...img import resources_rc
