# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\widgets\widget_27_7_21_err_devices.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_27_7_21_err_device(object):
    def setupUi(self, widget_27_7_21_err_device):
        widget_27_7_21_err_device.setObjectName("widget_27_7_21_err_device")
        widget_27_7_21_err_device.resize(440, 75)
        widget_27_7_21_err_device.setLayoutDirection(QtCore.Qt.LeftToRight)
        widget_27_7_21_err_device.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(47, 70, 105, 255), stop:1 rgba(131, 149, 174, 255));")
        self.lbl_name_error = QtWidgets.QLabel(widget_27_7_21_err_device)
        self.lbl_name_error.setEnabled(True)
        self.lbl_name_error.setGeometry(QtCore.QRect(5, 5, 271, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name_error.setFont(font)
        self.lbl_name_error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_name_error.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_name_error.setObjectName("lbl_name_error")
        self.lbl_info = QtWidgets.QLabel(widget_27_7_21_err_device)
        self.lbl_info.setEnabled(True)
        self.lbl_info.setGeometry(QtCore.QRect(160, 40, 65, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_info.setFont(font)
        self.lbl_info.setMouseTracking(True)
        self.lbl_info.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setStyleSheet("color: rgb(0, 49, 114);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_info.setLineWidth(1)
        self.lbl_info.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_info.setWordWrap(False)
        self.lbl_info.setIndent(0)
        self.lbl_info.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_info.setObjectName("lbl_info")
        self.lbl_data = QtWidgets.QLabel(widget_27_7_21_err_device)
        self.lbl_data.setEnabled(True)
        self.lbl_data.setGeometry(QtCore.QRect(230, 40, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_data.setFont(font)
        self.lbl_data.setMouseTracking(True)
        self.lbl_data.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lbl_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_data.setStyleSheet("color: rgb(0, 49, 114);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_data.setLineWidth(1)
        self.lbl_data.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_data.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_data.setWordWrap(False)
        self.lbl_data.setIndent(0)
        self.lbl_data.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_data.setObjectName("lbl_data")
        self.lbl_time = QtWidgets.QLabel(widget_27_7_21_err_device)
        self.lbl_time.setEnabled(True)
        self.lbl_time.setGeometry(QtCore.QRect(365, 40, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_time.setFont(font)
        self.lbl_time.setMouseTracking(True)
        self.lbl_time.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lbl_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_time.setStyleSheet("color: rgb(0, 49, 114);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_time.setLineWidth(1)
        self.lbl_time.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_time.setWordWrap(False)
        self.lbl_time.setIndent(0)
        self.lbl_time.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_time.setObjectName("lbl_time")

        self.retranslateUi(widget_27_7_21_err_device)
        QtCore.QMetaObject.connectSlotsByName(widget_27_7_21_err_device)

    def retranslateUi(self, widget_27_7_21_err_device):
        _translate = QtCore.QCoreApplication.translate
        widget_27_7_21_err_device.setWindowTitle(_translate("widget_27_7_21_err_device", "widget_27_7_21_err_devices"))
        self.lbl_name_error.setText(_translate("widget_27_7_21_err_device", "Ошибка устройства"))
        self.lbl_info.setText(_translate("widget_27_7_21_err_device", "Дата:"))
        self.lbl_data.setText(_translate("widget_27_7_21_err_device", "22.02.2024"))
        self.lbl_time.setText(_translate("widget_27_7_21_err_device", "22:22"))
