# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\widgets\widget_select_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_select_group(object):
    def setupUi(self, widget_select_group):
        widget_select_group.setObjectName("widget_select_group")
        widget_select_group.resize(450, 80)
        widget_select_group.setStyleSheet("QWidget{\n"
"    background-color: #1A4789;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"#background {\n"
"    color: #FFFFFF;\n"
"    background-color: #1A4789;\n"
"    border-width: 2px;\n"
"    border-style: groove;\n"
"    border-color: #ff9923;\n"
"    border-radius: 0px;\n"
"}")
        self.lbl_photo = QtWidgets.QLabel(widget_select_group)
        self.lbl_photo.setGeometry(QtCore.QRect(5, 5, 213, 70))
        self.lbl_photo.setText("")
        self.lbl_photo.setPixmap(QtGui.QPixmap("C:/Users/Admin/.designer/backup/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.lbl_photo.setScaledContents(True)
        self.lbl_photo.setObjectName("lbl_photo")
        self.name = QtWidgets.QLabel(widget_select_group)
        self.name.setGeometry(QtCore.QRect(5, 5, 430, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.name.setLineWidth(0)
        self.name.setMidLineWidth(0)
        self.name.setTextFormat(QtCore.Qt.AutoText)
        self.name.setPixmap(QtGui.QPixmap("ui\\widgets\\../../../../../../GUI/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.name.setScaledContents(True)
        self.name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name.setWordWrap(True)
        self.name.setOpenExternalLinks(False)
        self.name.setObjectName("name")
        self.background = QtWidgets.QLabel(widget_select_group)
        self.background.setGeometry(QtCore.QRect(0, 0, 450, 80))
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.background.setText("")
        self.background.setObjectName("background")
        self.lbl_count = QtWidgets.QLabel(widget_select_group)
        self.lbl_count.setEnabled(True)
        self.lbl_count.setGeometry(QtCore.QRect(215, 40, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_count.setFont(font)
        self.lbl_count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_count.setObjectName("lbl_count")
        self.count = QtWidgets.QLabel(widget_select_group)
        self.count.setEnabled(True)
        self.count.setGeometry(QtCore.QRect(300, 40, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.count.setFont(font)
        self.count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.count.setObjectName("count")
        self.background.raise_()
        self.lbl_photo.raise_()
        self.name.raise_()
        self.lbl_count.raise_()
        self.count.raise_()

        self.retranslateUi(widget_select_group)
        QtCore.QMetaObject.connectSlotsByName(widget_select_group)

    def retranslateUi(self, widget_select_group):
        _translate = QtCore.QCoreApplication.translate
        widget_select_group.setWindowTitle(_translate("widget_select_group", "widget_select_group"))
        self.name.setText(_translate("widget_select_group", "Фрезы"))
        self.lbl_count.setText(_translate("widget_select_group", "Всего:"))
        self.count.setText(_translate("widget_select_group", "2545"))
