# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_7_19_select_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_7_19_select_group(object):
    def setupUi(self, widget_7_19_select_group):
        widget_7_19_select_group.setObjectName("widget_7_19_select_group")
        widget_7_19_select_group.resize(440, 84)
        widget_7_19_select_group.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(47, 70, 105, 255), stop:1 rgba(131, 149, 174, 255));\n"
"border-color: rgb(0, 255, 0);")
        self.lbl_photo = QtWidgets.QLabel(widget_7_19_select_group)
        self.lbl_photo.setGeometry(QtCore.QRect(5, 5, 213, 70))
        self.lbl_photo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_photo.setText("")
        self.lbl_photo.setPixmap(QtGui.QPixmap("C:/Users/Admin/.designer/backup/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.lbl_photo.setScaledContents(True)
        self.lbl_photo.setObjectName("lbl_photo")
        self.lbl_name = QtWidgets.QLabel(widget_7_19_select_group)
        self.lbl_name.setGeometry(QtCore.QRect(215, 5, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(0, 49, 114);")
        self.lbl_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_name.setLineWidth(0)
        self.lbl_name.setMidLineWidth(0)
        self.lbl_name.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_name.setPixmap(QtGui.QPixmap("../../../../../../GUI/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.lbl_name.setScaledContents(True)
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setWordWrap(True)
        self.lbl_name.setOpenExternalLinks(False)
        self.lbl_name.setObjectName("lbl_name")
        self.label = QtWidgets.QLabel(widget_7_19_select_group)
        self.label.setGeometry(QtCore.QRect(2, 2, 437, 80))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.lbl_photo.raise_()
        self.lbl_name.raise_()

        self.retranslateUi(widget_7_19_select_group)
        QtCore.QMetaObject.connectSlotsByName(widget_7_19_select_group)

    def retranslateUi(self, widget_7_19_select_group):
        _translate = QtCore.QCoreApplication.translate
        widget_7_19_select_group.setWindowTitle(_translate("widget_7_19_select_group", "widget_7_19_select_group"))
        self.lbl_name.setText(_translate("widget_7_19_select_group", "Резец монолитный kghjhg"))
