# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_8_select_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_8_select_tool(object):
    def setupUi(self, screen_8_select_tool):
        screen_8_select_tool.setObjectName("screen_8_select_tool")
        screen_8_select_tool.resize(480, 800)
        screen_8_select_tool.setStyleSheet("background-color: #1A4789;")
        self.lbl_ico = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_ico.setGeometry(QtCore.QRect(260, 60, 210, 70))
        self.lbl_ico.setStyleSheet("color: #FFFFFF;\n"
"background-color: #1A4789;\n"
"border-width: 0px;\n"
"border-radius: 0px;")
        self.lbl_ico.setText("")
        self.lbl_ico.setPixmap(QtGui.QPixmap("C:/Users/Наташа/Desktop/гуй/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.lbl_ico.setScaledContents(True)
        self.lbl_ico.setObjectName("lbl_ico")
        self.btn_back = QtWidgets.QPushButton(screen_8_select_tool)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(5, 745, 470, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("color: #000000;\n"
"background-color: #86B7F4;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-color: #EAA657;\n"
"border-radius: 10px;")
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.listWidget = QtWidgets.QListWidget(screen_8_select_tool)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 130, 471, 601))
        self.listWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.listWidget.setObjectName("listWidget")
        self.lbl_info_1 = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_info_1.setEnabled(True)
        self.lbl_info_1.setGeometry(QtCore.QRect(10, 5, 361, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_1.setFont(font)
        self.lbl_info_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_1.setStyleSheet("color: #FFFFFF;\n"
"background-color: #1A4789;\n"
"border-width: 0px;\n"
"border-radius: 0px;")
        self.lbl_info_1.setObjectName("lbl_info_1")
        self.lbl_info_2 = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_info_2.setEnabled(True)
        self.lbl_info_2.setGeometry(QtCore.QRect(10, 45, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_2.setFont(font)
        self.lbl_info_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_2.setStyleSheet("color: #FFFFFF;\n"
"background-color: #1A4789;\n"
"border-width: 0px;\n"
"border-radius: 0px;")
        self.lbl_info_2.setObjectName("lbl_info_2")
        self.lbl_name_group = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_name_group.setEnabled(True)
        self.lbl_name_group.setGeometry(QtCore.QRect(10, 85, 460, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name_group.setFont(font)
        self.lbl_name_group.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_name_group.setStyleSheet("color: #FFFFFF;\n"
"background-color: #1A4789;\n"
"border-width: 0px;\n"
"border-radius: 0px;")
        self.lbl_name_group.setObjectName("lbl_name_group")

        self.retranslateUi(screen_8_select_tool)
        QtCore.QMetaObject.connectSlotsByName(screen_8_select_tool)

    def retranslateUi(self, screen_8_select_tool):
        _translate = QtCore.QCoreApplication.translate
        screen_8_select_tool.setWindowTitle(_translate("screen_8_select_tool", "screen_8_select_tool"))
        self.listWidget.setWhatsThis(_translate("screen_8_select_tool", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_info_1.setText(_translate("screen_8_select_tool", "Выбор инструмента"))
        self.lbl_info_2.setText(_translate("screen_8_select_tool", "Группа:"))
        self.lbl_name_group.setText(_translate("screen_8_select_tool", "Метчик"))
from ..img import resources_rc
