# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_8_select_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_8_select_tool(object):
    def setupUi(self, screen_8_select_tool):
        screen_8_select_tool.setObjectName("screen_8_select_tool")
        screen_8_select_tool.resize(480, 800)
        screen_8_select_tool.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"#background {\n"
"    color: #FFFFFF;\n"
"    background-color: #2e4461;\n"
"    border-width: 2px;\n"
"    border-style: groove;\n"
"    border-color: #ff9923;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-style: outset;\n"
"    border-color: #EAA657;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 25px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.lbl_ico = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_ico.setGeometry(QtCore.QRect(260, 60, 210, 70))
        self.lbl_ico.setText("")
        self.lbl_ico.setPixmap(QtGui.QPixmap("C:/Users/Наташа/Desktop/гуй/img/—Pngtree—original twist drill vector material_5752343.png"))
        self.lbl_ico.setScaledContents(True)
        self.lbl_ico.setObjectName("lbl_ico")
        self.btn_back = QtWidgets.QPushButton(screen_8_select_tool)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(5, 745, 470, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.listWidget = QtWidgets.QListWidget(screen_8_select_tool)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 140, 471, 591))
        self.listWidget.setObjectName("listWidget")
        self.lbl_info_1 = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_info_1.setEnabled(True)
        self.lbl_info_1.setGeometry(QtCore.QRect(10, 10, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_1.setFont(font)
        self.lbl_info_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_1.setObjectName("lbl_info_1")
        self.lbl_info_2 = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_info_2.setEnabled(True)
        self.lbl_info_2.setGeometry(QtCore.QRect(10, 50, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_2.setFont(font)
        self.lbl_info_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_2.setObjectName("lbl_info_2")
        self.tool_group = QtWidgets.QLabel(screen_8_select_tool)
        self.tool_group.setEnabled(True)
        self.tool_group.setGeometry(QtCore.QRect(10, 91, 460, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.tool_group.setFont(font)
        self.tool_group.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tool_group.setObjectName("tool_group")

        self.retranslateUi(screen_8_select_tool)
        QtCore.QMetaObject.connectSlotsByName(screen_8_select_tool)

    def retranslateUi(self, screen_8_select_tool):
        _translate = QtCore.QCoreApplication.translate
        screen_8_select_tool.setWindowTitle(_translate("screen_8_select_tool", "screen_8_select_tool"))
        self.listWidget.setWhatsThis(_translate("screen_8_select_tool", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_info_1.setText(_translate("screen_8_select_tool", "Выбор инструмента"))
        self.lbl_info_2.setText(_translate("screen_8_select_tool", "Группа:"))
        self.tool_group.setText(_translate("screen_8_select_tool", "Метчик"))
from ..img import resources_rc
