# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_8_select_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from GUI.helper.SvgToPng import SvgToPng
from GUI.ico.btn_ico_back import Back
from GUI.ico.btn_ico_down import Down
from GUI.ico.btn_ico_up import Up


class Ui_screen_8_select_tool(object):
    def set_pixmap_for_tool(self, svg_code):
        svg_to_png = SvgToPng()
        svg_to_png.src = svg_code
        self.lbl_ico.setPixmap(QtGui.QPixmap(svg_to_png.get_pixmap()))

    def setupUi(self, screen_8_select_tool):
        screen_8_select_tool.setObjectName("screen_8_select_tool")
        screen_8_select_tool.resize(480, 800)
        screen_8_select_tool.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(47, 70, 105, 255), stop:1 rgba(131, 149, 174, 255));")
        self.lbl_ico = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_ico.setGeometry(QtCore.QRect(260, 60, 210, 70))
        self.lbl_ico.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_ico.setText("")
        self.lbl_ico.setScaledContents(True)
        self.lbl_ico.setObjectName("lbl_ico")
        self.btn_up = QtWidgets.QPushButton(screen_8_select_tool)
        self.btn_up.setEnabled(True)
        self.btn_up.setGeometry(QtCore.QRect(5, 745, 153, 50))
        self.btn_up.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_up.setFont(font)
        self.btn_up.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_up.setText("")
        icon = QtGui.QIcon()  # "img/btn_ico_up.png"
        icon.addPixmap(QtGui.QPixmap(Up().get_pixmap()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon)
        self.btn_up.setIconSize(QtCore.QSize(51, 51))
        self.btn_up.setObjectName("btn_up")
        self.btn_back = QtWidgets.QPushButton(screen_8_select_tool)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(163, 745, 154, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_back.setText("")
        icon1 = QtGui.QIcon()  # "img/btn_ico_back.png"
        icon1.addPixmap(QtGui.QPixmap(Back().get_pixmap()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon1)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.listWidget = QtWidgets.QListWidget(screen_8_select_tool)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 130, 450, 610))
        self.listWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.listWidget.setObjectName("listWidget")
        self.btn_down = QtWidgets.QPushButton(screen_8_select_tool)
        self.btn_down.setEnabled(True)
        self.btn_down.setGeometry(QtCore.QRect(322, 745, 153, 50))
        self.btn_down.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_down.setFont(font)
        self.btn_down.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_down.setText("")
        icon2 = QtGui.QIcon()  # "img/btn_ico_down.png"
        icon2.addPixmap(QtGui.QPixmap(Down().get_pixmap()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon2)
        self.btn_down.setIconSize(QtCore.QSize(51, 51))
        self.btn_down.setObjectName("btn_down")
        self.lbl_info_1 = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_info_1.setEnabled(True)
        self.lbl_info_1.setGeometry(QtCore.QRect(10, 5, 361, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_1.setFont(font)
        self.lbl_info_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_1.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_info_1.setObjectName("lbl_info_1")
        self.lbl_info_2 = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_info_2.setEnabled(True)
        self.lbl_info_2.setGeometry(QtCore.QRect(10, 45, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_2.setFont(font)
        self.lbl_info_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_2.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_info_2.setObjectName("lbl_info_2")
        self.lbl_name_group = QtWidgets.QLabel(screen_8_select_tool)
        self.lbl_name_group.setEnabled(True)
        self.lbl_name_group.setGeometry(QtCore.QRect(10, 85, 460, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name_group.setFont(font)
        self.lbl_name_group.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_name_group.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_name_group.setObjectName("lbl_name_group")

        self.retranslateUi(screen_8_select_tool)
        QtCore.QMetaObject.connectSlotsByName(screen_8_select_tool)

    def retranslateUi(self, screen_8_select_tool):
        _translate = QtCore.QCoreApplication.translate
        screen_8_select_tool.setWindowTitle(_translate("screen_8_select_tool", "screen_8_select_tool"))
        self.listWidget.setWhatsThis(_translate("screen_8_select_tool", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_info_1.setText(_translate("screen_8_select_tool", "Выбор инструмента"))
        self.lbl_info_2.setText(_translate("screen_8_select_tool", "Группа:"))
        self.lbl_name_group.setText(_translate("screen_8_select_tool", "Метчик"))
