# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_21_summary_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_21_summary(object):
    def setupUi(self, screen_21_summary):
        screen_21_summary.setObjectName("screen_21_summary")
        screen_21_summary.resize(480, 800)
        screen_21_summary.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"#background {\n"
"    color: #FFFFFF;\n"
"    background-color: #2e4461;\n"
"    border-width: 2px;\n"
"    border-style: groove;\n"
"    border-color: #ff9923;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-style: outset;\n"
"    border-color: #EAA657;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 25px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.btn_up = QtWidgets.QPushButton(screen_21_summary)
        self.btn_up.setEnabled(True)
        self.btn_up.setGeometry(QtCore.QRect(5, 745, 153, 50))
        self.btn_up.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_up.setFont(font)
        self.btn_up.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon)
        self.btn_up.setIconSize(QtCore.QSize(51, 51))
        self.btn_up.setObjectName("btn_up")
        self.btn_back = QtWidgets.QPushButton(screen_21_summary)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(163, 745, 154, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon1)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.lbl_info_1 = QtWidgets.QLabel(screen_21_summary)
        self.lbl_info_1.setEnabled(True)
        self.lbl_info_1.setGeometry(QtCore.QRect(10, 5, 451, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_1.setFont(font)
        self.lbl_info_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_1.setObjectName("lbl_info_1")
        self.listWidget = QtWidgets.QListWidget(screen_21_summary)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 55, 471, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setAutoScroll(True)
        self.listWidget.setObjectName("listWidget")
        self.btn_down = QtWidgets.QPushButton(screen_21_summary)
        self.btn_down.setEnabled(True)
        self.btn_down.setGeometry(QtCore.QRect(322, 745, 153, 50))
        self.btn_down.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_down.setFont(font)
        self.btn_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon2)
        self.btn_down.setIconSize(QtCore.QSize(51, 51))
        self.btn_down.setObjectName("btn_down")

        self.retranslateUi(screen_21_summary)
        QtCore.QMetaObject.connectSlotsByName(screen_21_summary)

    def retranslateUi(self, screen_21_summary):
        _translate = QtCore.QCoreApplication.translate
        screen_21_summary.setWindowTitle(_translate("screen_21_summary", "screen_21_summary"))
        self.lbl_info_1.setText(_translate("screen_21_summary", "Сводка по истории операций"))
        self.listWidget.setWhatsThis(_translate("screen_21_summary", "<html><head/><body><p><br/></p></body></html>"))
from ..img import resources_rc
