# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_38_hal_coords.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_38_hal_coords(object):
    def setupUi(self, screen_38_hal_coords):
        screen_38_hal_coords.setObjectName("screen_38_hal_coords")
        screen_38_hal_coords.resize(480, 800)
        screen_38_hal_coords.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(screen_38_hal_coords)
        self.verticalLayout.setContentsMargins(12, 12, 12, 10)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(screen_38_hal_coords)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setStyleSheet("font-size: 26px; font-weight: 700;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.layout_cell_row = QtWidgets.QHBoxLayout()
        self.layout_cell_row.setObjectName("layout_cell_row")
        self.lbl_cell = QtWidgets.QLabel(screen_38_hal_coords)
        self.lbl_cell.setStyleSheet("font-size: 24px; font-weight: 600;")
        self.lbl_cell.setObjectName("lbl_cell")
        self.layout_cell_row.addWidget(self.lbl_cell)
        self.edit_cell_number = QtWidgets.QLineEdit(screen_38_hal_coords)
        self.edit_cell_number.setMinimumSize(QtCore.QSize(72, 30))
        self.edit_cell_number.setMaximumSize(QtCore.QSize(88, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.edit_cell_number.setFont(font)
        self.edit_cell_number.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_cell_number.setObjectName("edit_cell_number")
        self.layout_cell_row.addWidget(self.edit_cell_number)
        self.lbl_cell_mot_coords = QtWidgets.QLabel(screen_38_hal_coords)
        self.lbl_cell_mot_coords.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cell_mot_coords.setStyleSheet("color: #CCCCCC; font-size: 17px; font-weight: 600;")
        self.lbl_cell_mot_coords.setObjectName("lbl_cell_mot_coords")
        self.layout_cell_row.addWidget(self.lbl_cell_mot_coords)
        self.verticalLayout.addLayout(self.layout_cell_row)
        self.lbl_input_error = QtWidgets.QLabel(screen_38_hal_coords)
        self.lbl_input_error.setWordWrap(True)
        self.lbl_input_error.setStyleSheet("color: #ffb4b4; font-size: 16px; font-weight: 600;")
        self.lbl_input_error.setObjectName("lbl_input_error")
        self.verticalLayout.addWidget(self.lbl_input_error)
        self.layout_park_row = QtWidgets.QHBoxLayout()
        self.layout_park_row.setSpacing(8)
        self.layout_park_row.setObjectName("layout_park_row")
        self.btn_hal_park = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_hal_park.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022;border-radius: 8px; font-size: 20px; font-weight: 600; min-height: 48px; }")
        self.btn_hal_park.setObjectName("btn_hal_park")
        self.layout_park_row.addWidget(self.btn_hal_park)
        self.btn_hal_zero = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_hal_zero.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022;border-radius: 8px; font-size: 20px; font-weight: 600; min-height: 48px; }")
        self.btn_hal_zero.setObjectName("btn_hal_zero")
        self.layout_park_row.addWidget(self.btn_hal_zero)
        self.verticalLayout.addLayout(self.layout_park_row)
        spacerItem_jog = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem_jog)
        self.lbl_jog_title = QtWidgets.QLabel(screen_38_hal_coords)
        self.lbl_jog_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_jog_title.setStyleSheet("font-size: 20px; font-weight: 600;")
        self.lbl_jog_title.setObjectName("lbl_jog_title")
        self.verticalLayout.addWidget(self.lbl_jog_title)
        self.layout_jog_step_row = QtWidgets.QHBoxLayout()
        self.layout_jog_step_row.setSpacing(6)
        self.layout_jog_step_row.setObjectName("layout_jog_step_row")
        self.lbl_jog_step = QtWidgets.QLabel(screen_38_hal_coords)
        self.lbl_jog_step.setStyleSheet("font-size: 18px; font-weight: 600;")
        self.lbl_jog_step.setObjectName("lbl_jog_step")
        self.layout_jog_step_row.addWidget(self.lbl_jog_step)
        self._jog_step_btn_style = (
            "QPushButton { color: #FFFFFF; background-color: #f09022; border-radius: 8px;"
            " font-size: 18px; font-weight: 600; min-height: 40px; }\n"
            "QPushButton:checked { background-color: #c86a10; border: 2px solid #FFFFFF; }"
        )
        self.btn_jog_step_1 = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_jog_step_1.setCheckable(True)
        self.btn_jog_step_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_jog_step_1.setStyleSheet(self._jog_step_btn_style)
        self.btn_jog_step_1.setObjectName("btn_jog_step_1")
        self.layout_jog_step_row.addWidget(self.btn_jog_step_1)
        self.btn_jog_step_5 = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_jog_step_5.setCheckable(True)
        self.btn_jog_step_5.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_jog_step_5.setStyleSheet(self._jog_step_btn_style)
        self.btn_jog_step_5.setObjectName("btn_jog_step_5")
        self.layout_jog_step_row.addWidget(self.btn_jog_step_5)
        self.btn_jog_step_10 = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_jog_step_10.setCheckable(True)
        self.btn_jog_step_10.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_jog_step_10.setStyleSheet(self._jog_step_btn_style)
        self.btn_jog_step_10.setObjectName("btn_jog_step_10")
        self.layout_jog_step_row.addWidget(self.btn_jog_step_10)
        self.btn_jog_step_50 = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_jog_step_50.setCheckable(True)
        self.btn_jog_step_50.setChecked(True)
        self.btn_jog_step_50.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_jog_step_50.setStyleSheet(self._jog_step_btn_style)
        self.btn_jog_step_50.setObjectName("btn_jog_step_50")
        self.layout_jog_step_row.addWidget(self.btn_jog_step_50)
        self.btn_jog_step_100 = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_jog_step_100.setCheckable(True)
        self.btn_jog_step_100.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_jog_step_100.setStyleSheet(self._jog_step_btn_style)
        self.btn_jog_step_100.setObjectName("btn_jog_step_100")
        self.layout_jog_step_row.addWidget(self.btn_jog_step_100)
        self.verticalLayout.addLayout(self.layout_jog_step_row)
        self.widget_jog_placeholder = QtWidgets.QWidget(screen_38_hal_coords)
        self.widget_jog_placeholder.setMinimumSize(QtCore.QSize(0, 10))
        self.widget_jog_placeholder.setObjectName("widget_jog_placeholder")
        self.verticalLayout.addWidget(self.widget_jog_placeholder)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(screen_38_hal_coords)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)

        self.retranslateUi(screen_38_hal_coords)
        QtCore.QMetaObject.connectSlotsByName(screen_38_hal_coords)

    def retranslateUi(self, screen_38_hal_coords):
        _translate = QtCore.QCoreApplication.translate
        screen_38_hal_coords.setWindowTitle(_translate("screen_38_hal_coords", "screen_38_hal_coords"))
        self.lbl_title.setText(_translate("screen_38_hal_coords", "Координаты HAL"))
        self.lbl_cell.setText(_translate("screen_38_hal_coords", "Ячейка №"))
        self.lbl_cell_mot_coords.setText(_translate("screen_38_hal_coords", "(0, 0, 0)"))
        self.lbl_input_error.setText(_translate("screen_38_hal_coords", ""))
        self.btn_hal_park.setText(_translate("screen_38_hal_coords", "Парковка"))
        self.btn_hal_zero.setText(_translate("screen_38_hal_coords", "Нули"))
        self.lbl_jog_title.setText(_translate("screen_38_hal_coords", "JOG"))
        self.lbl_jog_step.setText(_translate("screen_38_hal_coords", "Шаг"))
        self.btn_jog_step_1.setText(_translate("screen_38_hal_coords", "1"))
        self.btn_jog_step_5.setText(_translate("screen_38_hal_coords", "5"))
        self.btn_jog_step_10.setText(_translate("screen_38_hal_coords", "10"))
        self.btn_jog_step_50.setText(_translate("screen_38_hal_coords", "50"))
        self.btn_jog_step_100.setText(_translate("screen_38_hal_coords", "100"))
from ..img import resources_rc
