# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_25_history_by_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_25_history_by_user(object):
    def setupUi(self, screen_25_history_by_user):
        screen_25_history_by_user.setObjectName("screen_25_history_by_user")
        screen_25_history_by_user.resize(480, 800)
        screen_25_history_by_user.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(47, 70, 105, 255), stop:1 rgba(131, 149, 174, 255));")
        self.ScrollBar = QtWidgets.QScrollBar(screen_25_history_by_user)
        self.ScrollBar.setGeometry(QtCore.QRect(460, 90, 15, 650))
        self.ScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.ScrollBar.setObjectName("ScrollBar")
        self.lbl_name_user = QtWidgets.QLabel(screen_25_history_by_user)
        self.lbl_name_user.setEnabled(True)
        self.lbl_name_user.setGeometry(QtCore.QRect(10, 45, 461, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name_user.setFont(font)
        self.lbl_name_user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_name_user.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_name_user.setObjectName("lbl_name_user")
        self.btn_up = QtWidgets.QPushButton(screen_25_history_by_user)
        self.btn_up.setEnabled(True)
        self.btn_up.setGeometry(QtCore.QRect(5, 745, 153, 50))
        self.btn_up.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_up.setFont(font)
        self.btn_up.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_up.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\img/btn_ico_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon)
        self.btn_up.setIconSize(QtCore.QSize(51, 51))
        self.btn_up.setObjectName("btn_up")
        self.btn_back = QtWidgets.QPushButton(screen_25_history_by_user)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(163, 745, 154, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\img/btn_ico_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon1)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.lbl_info = QtWidgets.QLabel(screen_25_history_by_user)
        self.lbl_info.setEnabled(True)
        self.lbl_info.setGeometry(QtCore.QRect(10, 5, 411, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info.setFont(font)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_info.setObjectName("lbl_info")
        self.btn_down = QtWidgets.QPushButton(screen_25_history_by_user)
        self.btn_down.setEnabled(True)
        self.btn_down.setGeometry(QtCore.QRect(322, 745, 153, 50))
        self.btn_down.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_down.setFont(font)
        self.btn_down.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\img/btn_ico_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon2)
        self.btn_down.setIconSize(QtCore.QSize(51, 51))
        self.btn_down.setObjectName("btn_down")
        self.listWidget = QtWidgets.QListWidget(screen_25_history_by_user)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 90, 450, 650))
        self.listWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(screen_25_history_by_user)
        QtCore.QMetaObject.connectSlotsByName(screen_25_history_by_user)

    def retranslateUi(self, screen_25_history_by_user):
        _translate = QtCore.QCoreApplication.translate
        screen_25_history_by_user.setWindowTitle(_translate("screen_25_history_by_user", "screen_25_history_by_user"))
        self.lbl_name_user.setText(_translate("screen_25_history_by_user", "Романов Александр Александрович"))
        self.lbl_info.setText(_translate("screen_25_history_by_user", "История операций"))
        self.listWidget.setWhatsThis(_translate("screen_25_history_by_user", "<html><head/><body><p><br/></p></body></html>"))
