# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_7_select_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_7_select_group(object):
    def setupUi(self, screen_7_select_group):
        screen_7_select_group.setObjectName("screen_7_select_group")
        screen_7_select_group.resize(480, 800)
        screen_7_select_group.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"#background {\n"
"    color: #FFFFFF;\n"
"    background-color: #2e4461;\n"
"    border-width: 2px;\n"
"    border-style: groove;\n"
"    border-color: #ff9923;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-style: outset;\n"
"    border-color: #EAA657;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 25px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.listWidget = QtWidgets.QListWidget(screen_7_select_group)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 50, 471, 681))
        self.listWidget.setObjectName("listWidget")
        self.btn_back = QtWidgets.QPushButton(screen_7_select_group)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(5, 745, 470, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.lbl_info = QtWidgets.QLabel(screen_7_select_group)
        self.lbl_info.setEnabled(True)
        self.lbl_info.setGeometry(QtCore.QRect(10, 5, 351, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info.setFont(font)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setObjectName("lbl_info")

        self.retranslateUi(screen_7_select_group)
        QtCore.QMetaObject.connectSlotsByName(screen_7_select_group)

    def retranslateUi(self, screen_7_select_group):
        _translate = QtCore.QCoreApplication.translate
        screen_7_select_group.setWindowTitle(_translate("screen_7_select_group", "screen_7_select_group"))
        self.listWidget.setWhatsThis(_translate("screen_7_select_group", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_info.setText(_translate("screen_7_select_group", "Выберите группу:"))
from ..img import resources_rc
