# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_37_engineer_hub.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_37_engineer_hub(object):
    def setupUi(self, screen_37_engineer_hub):
        screen_37_engineer_hub.setObjectName("screen_37_engineer_hub")
        screen_37_engineer_hub.resize(480, 800)
        screen_37_engineer_hub.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(screen_37_engineer_hub)
        self.verticalLayout.setContentsMargins(12, 16, 12, 10)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(screen_37_engineer_hub)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setStyleSheet("font-size: 30px; font-weight: 700;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_name = QtWidgets.QLabel(screen_37_engineer_hub)
        self.lbl_name.setText("")
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setStyleSheet("font-size: 22px;")
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.btn_hal_coords = QtWidgets.QPushButton(screen_37_engineer_hub)
        self.btn_hal_coords.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022;border-radius: 8px; font-size: 24px; font-weight: 600; min-height: 64px; }")
        self.btn_hal_coords.setObjectName("btn_hal_coords")
        self.verticalLayout.addWidget(self.btn_hal_coords)
        self.btn_hal_dispense = QtWidgets.QPushButton(screen_37_engineer_hub)
        self.btn_hal_dispense.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022;border-radius: 8px; font-size: 24px; font-weight: 600; min-height: 64px; }")
        self.btn_hal_dispense.setObjectName("btn_hal_dispense")
        self.verticalLayout.addWidget(self.btn_hal_dispense)
        self.btn_hal_cells_table = QtWidgets.QPushButton(screen_37_engineer_hub)
        self.btn_hal_cells_table.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022;border-radius: 8px; font-size: 24px; font-weight: 600; min-height: 64px; }")
        self.btn_hal_cells_table.setObjectName("btn_hal_cells_table")
        self.verticalLayout.addWidget(self.btn_hal_cells_table)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_back = QtWidgets.QPushButton(screen_37_engineer_hub)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)

        self.retranslateUi(screen_37_engineer_hub)
        QtCore.QMetaObject.connectSlotsByName(screen_37_engineer_hub)

    def retranslateUi(self, screen_37_engineer_hub):
        _translate = QtCore.QCoreApplication.translate
        screen_37_engineer_hub.setWindowTitle(_translate("screen_37_engineer_hub", "screen_37_engineer_hub"))
        self.lbl_title.setText(_translate("screen_37_engineer_hub", "Инженерное меню"))
        self.btn_hal_coords.setText(_translate("screen_37_engineer_hub", "Координаты"))
        self.btn_hal_dispense.setText(_translate("screen_37_engineer_hub", "Выдача"))
        self.btn_hal_cells_table.setText(_translate("screen_37_engineer_hub", "Таблица ячеек"))
from ..img import resources_rc
