# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_41_hal_cells_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_41_hal_cells_table(object):
    def setupUi(self, screen_41_hal_cells_table):
        screen_41_hal_cells_table.setObjectName("screen_41_hal_cells_table")
        screen_41_hal_cells_table.resize(480, 800)
        screen_41_hal_cells_table.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(screen_41_hal_cells_table)
        self.verticalLayout.setContentsMargins(12, 12, 12, 10)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(screen_41_hal_cells_table)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setStyleSheet("font-size: 26px; font-weight: 700;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.widget_table_header = QtWidgets.QWidget(screen_41_hal_cells_table)
        self.widget_table_header.setMinimumSize(QtCore.QSize(0, 44))
        self.widget_table_header.setMaximumSize(QtCore.QSize(16777215, 44))
        self.widget_table_header.setObjectName("widget_table_header")
        self.verticalLayout.addWidget(self.widget_table_header)
        self.listWidget = QtWidgets.QListWidget(screen_41_hal_cells_table)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setStyleSheet("QListWidget {\n"
"    border: none;\n"
"    background: transparent;\n"
"    outline: 0;\n"
"}\n"
"QListWidget::item {\n"
"    border: none;\n"
"    padding: 0px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.btn_back = QtWidgets.QPushButton(screen_41_hal_cells_table)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)

        self.retranslateUi(screen_41_hal_cells_table)
        QtCore.QMetaObject.connectSlotsByName(screen_41_hal_cells_table)

    def retranslateUi(self, screen_41_hal_cells_table):
        _translate = QtCore.QCoreApplication.translate
        screen_41_hal_cells_table.setWindowTitle(_translate("screen_41_hal_cells_table", "screen_41_hal_cells_table"))
        self.lbl_title.setText(_translate("screen_41_hal_cells_table", "Таблица HAL-координат"))
from ..img import resources_rc
