# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_27_history_err.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_27_history_err(object):
    def setupUi(self, screen_27_history_err):
        screen_27_history_err.setObjectName("screen_27_history_err")
        screen_27_history_err.resize(480, 800)
        screen_27_history_err.setStyleSheet("background-color: #1A4789;")
        self.btn_back = QtWidgets.QPushButton(screen_27_history_err)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(163, 745, 154, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("color: #000000;\n"
"background-color: #86B7F4;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-color: #EAA657;\n"
"border-radius: 10px;")
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.listWidget = QtWidgets.QListWidget(screen_27_history_err)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 50, 471, 690))
        self.listWidget.setStyleSheet("background-color: #1A4789; border-color: #EAA657;border-width: 2px;\n"
"border-style: outset;\n"
"border-color: #EAA657;")
        self.listWidget.setObjectName("listWidget")
        self.btn_up = QtWidgets.QPushButton(screen_27_history_err)
        self.btn_up.setEnabled(True)
        self.btn_up.setGeometry(QtCore.QRect(5, 745, 153, 50))
        self.btn_up.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_up.setFont(font)
        self.btn_up.setStyleSheet("color: #000000;\n"
"background-color: #86B7F4;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-color: #EAA657;\n"
"border-radius: 10px;")
        self.btn_up.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon1)
        self.btn_up.setIconSize(QtCore.QSize(51, 51))
        self.btn_up.setObjectName("btn_up")
        self.btn_down = QtWidgets.QPushButton(screen_27_history_err)
        self.btn_down.setEnabled(True)
        self.btn_down.setGeometry(QtCore.QRect(322, 745, 153, 50))
        self.btn_down.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_down.setFont(font)
        self.btn_down.setStyleSheet("color: #000000;\n"
"background-color: #86B7F4;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-color: #EAA657;\n"
"border-radius: 10px;")
        self.btn_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon2)
        self.btn_down.setIconSize(QtCore.QSize(51, 51))
        self.btn_down.setObjectName("btn_down")
        self.lbl_info = QtWidgets.QLabel(screen_27_history_err)
        self.lbl_info.setEnabled(True)
        self.lbl_info.setGeometry(QtCore.QRect(10, 5, 311, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info.setFont(font)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setStyleSheet("color: white;\n"
"background-color: #1A4789;")
        self.lbl_info.setObjectName("lbl_info")

        self.retranslateUi(screen_27_history_err)
        QtCore.QMetaObject.connectSlotsByName(screen_27_history_err)

    def retranslateUi(self, screen_27_history_err):
        _translate = QtCore.QCoreApplication.translate
        screen_27_history_err.setWindowTitle(_translate("screen_27_history_err", "screen_27_history_err"))
        self.listWidget.setWhatsThis(_translate("screen_27_history_err", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_info.setText(_translate("screen_27_history_err", "История ошибок"))
from ..img import resources_rc
