# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_40_hal_dispense.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_40_hal_dispense(object):
    def setupUi(self, screen_40_hal_dispense):
        screen_40_hal_dispense.setObjectName("screen_40_hal_dispense")
        screen_40_hal_dispense.resize(480, 800)
        screen_40_hal_dispense.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(screen_40_hal_dispense)
        self.verticalLayout.setContentsMargins(12, 16, 12, 10)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(screen_40_hal_dispense)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setStyleSheet("font-size: 23px; font-weight: 700;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_hint = QtWidgets.QLabel(screen_40_hal_dispense)
        self.lbl_hint.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hint.setStyleSheet("color: #CCCCCC; font-size: 13px;")
        self.lbl_hint.setObjectName("lbl_hint")
        self.verticalLayout.addWidget(self.lbl_hint)
        self.layout_cell_row = QtWidgets.QHBoxLayout()
        self.layout_cell_row.setSpacing(8)
        self.layout_cell_row.setObjectName("layout_cell_row")
        self.lbl_cell = QtWidgets.QLabel(screen_40_hal_dispense)
        self.lbl_cell.setMinimumSize(QtCore.QSize(96, 48))
        self.lbl_cell.setStyleSheet("font-size: 18px; font-weight: 600;")
        self.lbl_cell.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.lbl_cell.setObjectName("lbl_cell")
        self.layout_cell_row.addWidget(self.lbl_cell)
        self.edit_cell_number = QtWidgets.QLineEdit(screen_40_hal_dispense)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        self.edit_cell_number.setSizePolicy(sizePolicy)
        self.edit_cell_number.setMinimumSize(QtCore.QSize(64, 48))
        self.edit_cell_number.setMaxLength(4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.edit_cell_number.setFont(font)
        self.edit_cell_number.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_cell_number.setObjectName("edit_cell_number")
        self.layout_cell_row.addWidget(self.edit_cell_number)
        self.btn_hal_dispense_run = QtWidgets.QPushButton(screen_40_hal_dispense)
        self.btn_hal_dispense_run.setMinimumSize(QtCore.QSize(104, 48))
        self.btn_hal_dispense_run.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022; border-radius: 8px; font-size: 17px; font-weight: 600; }")
        self.btn_hal_dispense_run.setObjectName("btn_hal_dispense_run")
        self.layout_cell_row.addWidget(self.btn_hal_dispense_run)
        self.verticalLayout.addLayout(self.layout_cell_row)
        self.lbl_input_error = QtWidgets.QLabel(screen_40_hal_dispense)
        self.lbl_input_error.setWordWrap(True)
        self.lbl_input_error.setStyleSheet("color: #ffb4b4; font-size: 11px; font-weight: 600;")
        self.lbl_input_error.setObjectName("lbl_input_error")
        self.verticalLayout.addWidget(self.lbl_input_error)
        self.lbl_park_title = QtWidgets.QLabel(screen_40_hal_dispense)
        self.lbl_park_title.setStyleSheet("font-size: 19px; font-weight: 600;")
        self.lbl_park_title.setObjectName("lbl_park_title")
        self.verticalLayout.addWidget(self.lbl_park_title)
        self.widget_park_rows = QtWidgets.QWidget(screen_40_hal_dispense)
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.widget_park_rows.setSizePolicy(sizePolicy1)
        self.widget_park_rows.setObjectName("widget_park_rows")
        self.verticalLayout.addWidget(self.widget_park_rows)
        self.lbl_rgb_title = QtWidgets.QLabel(screen_40_hal_dispense)
        self.lbl_rgb_title.setStyleSheet("font-size: 19px; font-weight: 600;")
        self.lbl_rgb_title.setObjectName("lbl_rgb_title")
        self.verticalLayout.addWidget(self.lbl_rgb_title)
        self.widget_rgb_rows = QtWidgets.QWidget(screen_40_hal_dispense)
        sizePolicy2 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.widget_rgb_rows.setSizePolicy(sizePolicy2)
        self.widget_rgb_rows.setObjectName("widget_rgb_rows")
        self.verticalLayout.addWidget(self.widget_rgb_rows)
        self.lbl_lock_title = QtWidgets.QLabel(screen_40_hal_dispense)
        self.lbl_lock_title.setStyleSheet("font-size: 19px; font-weight: 600;")
        self.lbl_lock_title.setObjectName("lbl_lock_title")
        self.verticalLayout.addWidget(self.lbl_lock_title)
        self.layout_actuator_row = QtWidgets.QHBoxLayout()
        self.layout_actuator_row.setSpacing(8)
        self.layout_actuator_row.setObjectName("layout_actuator_row")
        self.btn_hal_solenoid = QtWidgets.QPushButton(screen_40_hal_dispense)
        self.btn_hal_solenoid.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022; border-radius: 8px; font-size: 19px; font-weight: 600; min-height: 43px; }")
        self.btn_hal_solenoid.setObjectName("btn_hal_solenoid")
        self.layout_actuator_row.addWidget(self.btn_hal_solenoid)
        self.btn_hal_lock = QtWidgets.QPushButton(screen_40_hal_dispense)
        self.btn_hal_lock.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022; border-radius: 8px; font-size: 19px; font-weight: 600; min-height: 43px; }")
        self.btn_hal_lock.setObjectName("btn_hal_lock")
        self.layout_actuator_row.addWidget(self.btn_hal_lock)
        self.verticalLayout.addLayout(self.layout_actuator_row)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(screen_40_hal_dispense)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 45))
        self.btn_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon1)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        self.btn_hal_park_save = QtWidgets.QPushButton(screen_40_hal_dispense)
        self.btn_hal_park_save.setVisible(False)
        self.btn_hal_park_save.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022; border-radius: 8px; font-size: 17px; font-weight: 600; min-height: 48px; }")
        self.btn_hal_park_save.setObjectName("btn_hal_park_save")
        self.btn_hal_rgb_save = QtWidgets.QPushButton(screen_40_hal_dispense)
        self.btn_hal_rgb_save.setVisible(False)
        self.btn_hal_rgb_save.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022; border-radius: 8px; font-size: 17px; font-weight: 600; min-height: 48px; }")
        self.btn_hal_rgb_save.setObjectName("btn_hal_rgb_save")
        self.btn_hal_led = QtWidgets.QPushButton(screen_40_hal_dispense)
        self.btn_hal_led.setVisible(False)
        self.btn_hal_led.setText("")
        self.btn_hal_led.setStyleSheet("QPushButton { color: #FFFFFF; background-color: #f09022; border-radius: 8px; font-size: 19px; font-weight: 600; min-height: 43px; }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/power_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hal_led.setIcon(icon2)
        self.btn_hal_led.setIconSize(QtCore.QSize(28, 28))
        self.btn_hal_led.setObjectName("btn_hal_led")

        self.retranslateUi(screen_40_hal_dispense)
        QtCore.QMetaObject.connectSlotsByName(screen_40_hal_dispense)

    def retranslateUi(self, screen_40_hal_dispense):
        _translate = QtCore.QCoreApplication.translate
        screen_40_hal_dispense.setWindowTitle(_translate("screen_40_hal_dispense", "screen_40_hal_dispense"))
        self.lbl_title.setText(_translate("screen_40_hal_dispense", "Тестовая выдача"))
        self.lbl_hint.setText(_translate("screen_40_hal_dispense", "Введите номер ячейки. Расход не списывается."))
        self.lbl_cell.setText(_translate("screen_40_hal_dispense", "Ячейка №"))
        self.lbl_park_title.setText(_translate("screen_40_hal_dispense", "Парковка MOT"))
        self.lbl_rgb_title.setText(_translate("screen_40_hal_dispense", "Подсветка"))
        self.lbl_lock_title.setText(_translate("screen_40_hal_dispense", "Замки"))
        self.btn_hal_park_save.setText(_translate("screen_40_hal_dispense", "Сохранить"))
        self.btn_hal_rgb_save.setText(_translate("screen_40_hal_dispense", "Сохранить"))
        self.btn_hal_solenoid.setText(_translate("screen_40_hal_dispense", "Соленоид"))
        self.btn_hal_lock.setText(_translate("screen_40_hal_dispense", "Замки"))
        self.btn_hal_dispense_run.setText(_translate("screen_40_hal_dispense", "Выдать"))
from ..img import resources_rc
