# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_19_management_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_19_management_group(object):
    def setupUi(self, screen_19_management_group):
        screen_19_management_group.setObjectName("screen_19_management_group")
        screen_19_management_group.resize(480, 800)
        screen_19_management_group.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"#background {\n"
"    color: #FFFFFF;\n"
"    background-color: #2e4461;\n"
"    border-width: 2px;\n"
"    border-style: groove;\n"
"    border-color: #ff9923;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-style: outset;\n"
"    border-color: #EAA657;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 25px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.listWidget = QtWidgets.QListWidget(screen_19_management_group)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 90, 471, 650))
        self.listWidget.setObjectName("listWidget")
        self.lbl_info_2 = QtWidgets.QLabel(screen_19_management_group)
        self.lbl_info_2.setEnabled(True)
        self.lbl_info_2.setGeometry(QtCore.QRect(10, 45, 261, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_2.setFont(font)
        self.lbl_info_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_2.setObjectName("lbl_info_2")
        self.lbl_info_1 = QtWidgets.QLabel(screen_19_management_group)
        self.lbl_info_1.setEnabled(True)
        self.lbl_info_1.setGeometry(QtCore.QRect(10, 5, 411, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_1.setFont(font)
        self.lbl_info_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info_1.setObjectName("lbl_info_1")
        self.btn_down = QtWidgets.QPushButton(screen_19_management_group)
        self.btn_down.setEnabled(True)
        self.btn_down.setGeometry(QtCore.QRect(322, 745, 153, 50))
        self.btn_down.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_down.setFont(font)
        self.btn_down.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon)
        self.btn_down.setIconSize(QtCore.QSize(51, 51))
        self.btn_down.setObjectName("btn_down")
        self.btn_up = QtWidgets.QPushButton(screen_19_management_group)
        self.btn_up.setEnabled(True)
        self.btn_up.setGeometry(QtCore.QRect(5, 745, 153, 50))
        self.btn_up.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_up.setFont(font)
        self.btn_up.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon1)
        self.btn_up.setIconSize(QtCore.QSize(51, 51))
        self.btn_up.setObjectName("btn_up")
        self.btn_back = QtWidgets.QPushButton(screen_19_management_group)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(163, 745, 154, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon2)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(screen_19_management_group)
        QtCore.QMetaObject.connectSlotsByName(screen_19_management_group)

    def retranslateUi(self, screen_19_management_group):
        _translate = QtCore.QCoreApplication.translate
        screen_19_management_group.setWindowTitle(_translate("screen_19_management_group", "screen_19_management_group"))
        self.listWidget.setWhatsThis(_translate("screen_19_management_group", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_info_2.setText(_translate("screen_19_management_group", "Выберите группу:"))
        self.lbl_info_1.setText(_translate("screen_19_management_group", "Управление запасами"))
from ..img import resources_rc
