# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\screen_27_history_err.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_27_history_err(object):
    def setupUi(self, screen_27_history_err):
        screen_27_history_err.setObjectName("screen_27_history_err")
        screen_27_history_err.resize(480, 800)
        screen_27_history_err.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(47, 70, 105, 255), stop:1 rgba(131, 149, 174, 255));")
        self.btn_back = QtWidgets.QPushButton(screen_27_history_err)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(163, 745, 154, 50))
        self.btn_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\img/btn_ico_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.listWidget = QtWidgets.QListWidget(screen_27_history_err)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(5, 50, 471, 690))
        self.listWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.listWidget.setObjectName("listWidget")
        self.btn_up = QtWidgets.QPushButton(screen_27_history_err)
        self.btn_up.setEnabled(True)
        self.btn_up.setGeometry(QtCore.QRect(5, 745, 153, 50))
        self.btn_up.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_up.setFont(font)
        self.btn_up.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_up.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\img/btn_ico_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon1)
        self.btn_up.setIconSize(QtCore.QSize(51, 51))
        self.btn_up.setObjectName("btn_up")
        self.btn_down = QtWidgets.QPushButton(screen_27_history_err)
        self.btn_down.setEnabled(True)
        self.btn_down.setGeometry(QtCore.QRect(322, 745, 153, 50))
        self.btn_down.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_down.setFont(font)
        self.btn_down.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(131, 173, 239, 255), stop:1 rgba(120, 158, 217, 255));\n"
"color: rgb(0, 49, 114);")
        self.btn_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\img/btn_ico_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon2)
        self.btn_down.setIconSize(QtCore.QSize(51, 51))
        self.btn_down.setObjectName("btn_down")
        self.lbl_info = QtWidgets.QLabel(screen_27_history_err)
        self.lbl_info.setEnabled(True)
        self.lbl_info.setGeometry(QtCore.QRect(10, 5, 311, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info.setFont(font)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setStyleSheet("color: rgb(78, 155, 229);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.lbl_info.setObjectName("lbl_info")

        self.retranslateUi(screen_27_history_err)
        QtCore.QMetaObject.connectSlotsByName(screen_27_history_err)

    def retranslateUi(self, screen_27_history_err):
        _translate = QtCore.QCoreApplication.translate
        screen_27_history_err.setWindowTitle(_translate("screen_27_history_err", "screen_27_history_err"))
        self.listWidget.setWhatsThis(_translate("screen_27_history_err", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_info.setText(_translate("screen_27_history_err", "История ошибок"))
