# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/ui/screen_42_hal_terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_42_hal_terminal(object):
    def setupUi(self, screen_42_hal_terminal):
        screen_42_hal_terminal.setObjectName("screen_42_hal_terminal")
        screen_42_hal_terminal.resize(480, 800)
        screen_42_hal_terminal.setStyleSheet("QWidget{\n"
"    background-color: #2e4461;\n"
"}\n"
"QLabel {\n"
"    background: none;\n"
"    color: #FFFFFF;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #f09022;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    font-family: \"Roboto\", Sans-serif;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(screen_42_hal_terminal)
        self.verticalLayout.setContentsMargins(12, 12, 12, 10)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(screen_42_hal_terminal)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setStyleSheet("font-size: 26px; font-weight: 700;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_status = QtWidgets.QLabel(screen_42_hal_terminal)
        self.lbl_status.setStyleSheet("font-size: 14px; color: #a8c0d8;")
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout.addWidget(self.lbl_status)
        self.te_log = QtWidgets.QPlainTextEdit(screen_42_hal_terminal)
        self.te_log.setReadOnly(True)
        self.te_log.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.te_log.setStyleSheet("QPlainTextEdit {\n"
"    color: #e8f0f8;\n"
"    background-color: #1a2838;\n"
"    border: 1px solid #4a6a8a;\n"
"    border-radius: 6px;\n"
"    font-family: \"Consolas\", \"Courier New\", monospace;\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}")
        self.te_log.setObjectName("te_log")
        self.verticalLayout.addWidget(self.te_log)
        self.edit_cmd = QtWidgets.QLineEdit(screen_42_hal_terminal)
        self.edit_cmd.setStyleSheet("QLineEdit {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e3350;\n"
"    border: 1px solid #4a6a8a;\n"
"    border-radius: 6px;\n"
"    font-family: \"Consolas\", \"Courier New\", monospace;\n"
"    font-size: 16px;\n"
"    padding: 8px;\n"
"}")
        self.edit_cmd.setObjectName("edit_cmd")
        self.verticalLayout.addWidget(self.edit_cmd)
        self.layout_actions = QtWidgets.QHBoxLayout()
        self.layout_actions.setSpacing(8)
        self.layout_actions.setObjectName("layout_actions")
        self.btn_clear = QtWidgets.QPushButton(screen_42_hal_terminal)
        self.btn_clear.setMinimumSize(QtCore.QSize(0, 44))
        self.btn_clear.setStyleSheet("QPushButton { font-size: 18px; min-height: 44px; }")
        self.btn_clear.setObjectName("btn_clear")
        self.layout_actions.addWidget(self.btn_clear)
        self.btn_help = QtWidgets.QPushButton(screen_42_hal_terminal)
        self.btn_help.setMinimumSize(QtCore.QSize(0, 44))
        self.btn_help.setStyleSheet("QPushButton { font-size: 18px; min-height: 44px; }")
        self.btn_help.setObjectName("btn_help")
        self.layout_actions.addWidget(self.btn_help)
        self.verticalLayout.addLayout(self.layout_actions)
        self.btn_back = QtWidgets.QPushButton(screen_42_hal_terminal)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(51, 51))
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)

        self.retranslateUi(screen_42_hal_terminal)
        QtCore.QMetaObject.connectSlotsByName(screen_42_hal_terminal)

    def retranslateUi(self, screen_42_hal_terminal):
        _translate = QtCore.QCoreApplication.translate
        screen_42_hal_terminal.setWindowTitle(_translate("screen_42_hal_terminal", "screen_42_hal_terminal"))
        self.lbl_title.setText(_translate("screen_42_hal_terminal", "Терминал"))
        self.lbl_status.setText(_translate("screen_42_hal_terminal", "Подключение…"))
        self.edit_cmd.setPlaceholderText(_translate("screen_42_hal_terminal", "Команда (Enter — отправить)"))
        self.btn_clear.setText(_translate("screen_42_hal_terminal", "Очистить"))
        self.btn_help.setText(_translate("screen_42_hal_terminal", "Справка"))
from ..img import resources_rc
